# blagues.py - Liste de blagues en français
# Chaque blague est un dictionnaire avec :
#   "question" : la mise en place (ce qui est dit en premier)
#   "reponse"  : la chute (dite après une petite pause)

blagues = [
    {"question": "Qu'est-ce qui est jaune et qui attend ?", "reponse": "Jonathan !"},
    {"question": "Qu'est-ce qui est vert et qui monte et qui descend ?", "reponse": "Un petit pois dans un ascenseur."},
    {"question": "Qu'est-ce qui est rouge et qui monte et qui descend ?", "reponse": "Une tomate dans un ascenseur."},
    {"question": "Qu'est-ce qui est jaune et qui court très vite ?", "reponse": "Un citron pressé !"},
    {"question": "Qu'est-ce qui est transparent et qui sent la carotte ?", "reponse": "Un pet de lapin."},
    {"question": "Qu'est-ce qui est petit, marron et qui grimpe aux arbres ?", "reponse": "Un marron qui a perdu son arbre et qui rentre à la maison."},
    {"question": "Qu'est-ce qui est vert et qui devient rouge quand on appuie sur un bouton ?", "reponse": "Une grenouille dans un mixeur."},
    {"question": "Qu'est-ce qui est jaune et qui pique ?", "reponse": "Une abeille en colère."},
    {"question": "Qu'est-ce qui est blanc et qui monte ?", "reponse": "Un idiot dans un ascenseur."},
    {"question": "Qu'est-ce qui est gris, avec une trompe et qui vole à 500 km heure ?", "reponse": "Un éléphant en avion !"},

    {"question": "Pourquoi les plongeurs plongent-ils toujours en arrière ?", "reponse": "Parce que sinon, ils tombent dans le bateau."},
    {"question": "Pourquoi les pompiers ont-ils des bretelles rouges ?", "reponse": "Pour tenir leur pantalon !"},
    {"question": "Pourquoi les canards sont-ils toujours à l'heure ?", "reponse": "Parce qu'ils sont dans l'étang !"},
    {"question": "Pourquoi les poissons détestent-ils les ordinateurs ?", "reponse": "Parce qu'ils ont peur du net !"},
    {"question": "Pourquoi les éléphants ne peuvent pas monter aux arbres ?", "reponse": "Parce qu'ils n'ont pas la carte bleue."},
    {"question": "Pourquoi les girafes ont-elles un long cou ?", "reponse": "Parce qu'elles ont les pieds qui puent !"},
    {"question": "Pourquoi les moutons ne font-ils pas de bruit quand ils rentrent chez eux ?", "reponse": "Parce qu'ils portent des chaussons."},
    {"question": "Pourquoi les vaches ferment-elles les yeux pour traire ?", "reponse": "Pour faire du lait concentré."},
    {"question": "Pourquoi les mathématiciens confondent Halloween et Noël ?", "reponse": "Parce qu'Octobre 31 égale Décembre 25 !"},
    {"question": "Pourquoi les piments rouges rougissent-ils ?", "reponse": "Parce qu'ils voient la salade se faire assaisonner."},

    {"question": "Quelle est la différence entre un hibou et un courant d'air ?", "reponse": "Le hibou hulule, alors que le courant d'air hulule-ule !"},
    {"question": "Quelle est la différence entre un parisien et un yaourt ?", "reponse": "Au bout d'un certain temps, le yaourt devient moins aigri."},
    {"question": "Quelle est la différence entre un radiateur et un chauffage ?", "reponse": "Aucune, mais pour un radiateur on est sûr."},
    {"question": "Quelle est la différence entre une pizza et un musicien ?", "reponse": "Une pizza peut nourrir une famille de quatre personnes."},
    {"question": "Quelle est la différence entre une gare et une salle de concert ?", "reponse": "Dans une gare, il y a marqué défense de cracher."},
    {"question": "Quelle est la différence entre un éléphant et un biscuit ?", "reponse": "Essaie donc de tremper un éléphant dans ton café !"},
    {"question": "Quelle est la différence entre un crocodile et un alligator ?", "reponse": "L'un voit plus tard et l'autre voit un peu plus tôt !"},
    {"question": "Quelle est la différence entre un boxeur et un enrhumé ?", "reponse": "Le boxeur encaisse les coups, l'enrhumé se mouche."},

    {"question": "Que fait une fraise sur un cheval ?", "reponse": "Tagada tagada !"},
    {"question": "Que dit un oignon quand il se cogne ?", "reponse": "Aïe !"},
    {"question": "Que dit un escargot quand il croise une limace ?", "reponse": "Regarde, un nudiste !"},
    {"question": "Que dit un Japonais quand on lui pique son vélo ?", "reponse": "Ma-zda !"},
    {"question": "Que dit un crocodile qui fait de la politique ?", "reponse": "Je suis un homme d'État !"},
    {"question": "Que dit une maman guêpe à sa petite guêpe qui ne veut pas aller à l'école ?", "reponse": "Mais enfin, c'est essen-tiel !"},
    {"question": "Que dit un informaticien qui s'ennuie au travail ?", "reponse": "C'est souris !"},

    {"question": "Comment appelle-t-on un chat tombé dans un pot de peinture le jour de Noël ?", "reponse": "Un chat peint de Noël !"},
    {"question": "Comment appelle-t-on un chien sans pattes ?", "reponse": "On ne l'appelle pas, on va le chercher."},
    {"question": "Comment appelle-t-on une fourmi dans l'espace ?", "reponse": "Une cosmo-fourmi !"},
    {"question": "Comment appelle-t-on une personne qui a peur du Père Noël ?", "reponse": "Un claustrophobe !"},
    {"question": "Comment reconnaît-on un informaticien déprimé ?", "reponse": "Il regarde fixement ses chaussures. Un informaticien heureux, lui, regarde fixement VOS chaussures."},
    {"question": "Comment appelle-t-on un poisson qui parle ?", "reponse": "Un perroqué !"},
    {"question": "Comment appelle-t-on un rappeur chez le dentiste ?", "reponse": "Un rappeur qui fait ses molaires !"},

    {"question": "Un squelette entre dans un bar et commande...", "reponse": "Une bière et une serpillière."},
    {"question": "Deux baguettes entrent dans une boulangerie. Laquelle parle en premier ?", "reponse": "Aucune, les baguettes ne parlent pas !"},
    {"question": "Deux cacahuètes marchent dans la rue. L'une d'elles se fait agresser...", "reponse": "Cacahuète assaillie !"},
    {"question": "Un homme entre dans un café.", "reponse": "Plouf !"},
    {"question": "Un zéro rencontre un huit et lui dit...", "reponse": "Hey, t'es bien sapé toi, avec ta ceinture !"},
    {"question": "Deux asticots sont dans une pomme. L'un dit à l'autre :", "reponse": "Il fait sombre ici ! Oui, surtout quand on ferme les yeux !"},
    {"question": "C'est deux poissons dans un bocal. L'un dit à l'autre :", "reponse": "Tu sais conduire toi ? Parce que moi j'ai pas le permis !"},

    {"question": "La maîtresse demande à Toto : Conjugue le verbe marcher au présent. Toto répond :", "reponse": "Je marche, tu marches... Plus vite Toto ! Je cours, tu cours..."},
    {"question": "Maman, à l'école on m'appelle Lucky Luke ! dit Toto. La mère répond :", "reponse": "Dis-leur d'arrêter Toto, dépêche ! Plus vite que son ombre !"},
    {"question": "Toto, pourquoi es-tu en retard à l'école ? Toto répond :", "reponse": "J'ai rêvé d'un match de foot madame, et il y a eu des prolongations !"},
    {"question": "Toto, pourquoi as-tu zéro en géographie ? Parce que madame,", "reponse": "Vous avez dit que la Terre tournait, alors j'ai attendu que ma copie revienne !"},

    {"question": "Quel est le sport le plus silencieux ?", "reponse": "Le para-chuuuut !"},
    {"question": "Quel est le sport le plus fruité ?", "reponse": "La boxe... parce qu'on met des pêches !"},
    {"question": "Quel est le comble pour un électricien ?", "reponse": "C'est de ne pas être au courant."},
    {"question": "Quel est le comble pour un jardinier ?", "reponse": "Raconter des salades."},
    {"question": "Quel est le comble pour un boulanger ?", "reponse": "Ne pas être dans son pétrin."},
    {"question": "Quel est le comble pour un menteur ?", "reponse": "Avoir un accent vrai."},
    {"question": "Quel est le comble pour un magicien ?", "reponse": "Se faire disparaître sans le faire exprès."},
    {"question": "Quel est le comble pour un cordonnier ?", "reponse": "Mourir de faim avec toutes ses semelles !"},

    {"question": "Monsieur et Madame Térieur ont une fille. Comment s'appelle-t-elle ?", "reponse": "Alex ! Alex Térieur !"},
    {"question": "Monsieur et Madame Ficelle ont un fils. Comment s'appelle-t-il ?", "reponse": "Jean ! Jean Ficelle !"},
    {"question": "Monsieur et Madame Achère ont une fille. Comment s'appelle-t-elle ?", "reponse": "Sophie ! Sophie Achère !"},
    {"question": "Monsieur et Madame Oiseau ont un fils. Comment s'appelle-t-il ?", "reponse": "Lou ! Lou Oiseau !"},
    {"question": "Monsieur et Madame Uzi ont un fils. Comment s'appelle-t-il ?", "reponse": "Jacques ! Jacques Uzi !"},
    {"question": "Monsieur et Madame Térieur ont un deuxième enfant. Comment s'appelle-t-il ?", "reponse": "Alain ! Alain Térieur !"},
    {"question": "Monsieur et Madame Pon ont une fille. Comment s'appelle-t-elle ?", "reponse": "Nathalie ! Nathalie Pon !"},
    {"question": "Monsieur et Madame Ginal ont un fils. Comment s'appelle-t-il ?", "reponse": "Auguste ! Auguste Ginal !"},
    {"question": "Monsieur et Madame Sapatro ont un fils. Comment s'appelle-t-il ?", "reponse": "Jean ! Jean Sapatro !"},

    {"question": "Qu'est-ce qu'un chat qui traverse un champ de maïs ?", "reponse": "Un pop-chat !"},
    {"question": "Qu'est-ce qu'un cannibale qui mange sa mère ?", "reponse": "Un orphelin !"},
    {"question": "Qu'est-ce qu'un crocodile à Paris ?", "reponse": "Perdu !"},
    {"question": "Qu'est-ce qui voyage autour du monde en restant dans son coin ?", "reponse": "Un timbre-poste."},
    {"question": "Qu'est-ce qui pique sans être une abeille ?", "reponse": "Un voleur."},
    {"question": "Qu'est-ce qu'une chauve-souris ?", "reponse": "Un rongeur qui a perdu ses cheveux."},
    {"question": "Qu'est-ce qu'un pull qui a fait Harvard ?", "reponse": "Un pull-over cultivé."},

    {"question": "Un Français et un Belge sont dans un avion. Le Français demande : Vous allez où ? Le Belge répond :", "reponse": "Je sais pas, je suis pas le pilote."},
    {"question": "Comment reconnaît-on un Belge au supermarché ?", "reponse": "C'est celui qui souffle dans les caddies pour enlever la neige... en été."},
    {"question": "Pourquoi les Belges mettent-ils deux cartouches dans leur fusil ?", "reponse": "Au cas où le premier coup ferait pschitt !"},

    {"question": "Pourquoi les vampires ne se marient-ils pas ?", "reponse": "Parce que le mariage, c'est pour la vie !"},
    {"question": "Pourquoi les fantômes ont-ils toujours froid ?", "reponse": "Parce qu'ils portent des draps."},
    {"question": "Pourquoi les sorcières ne montent-elles pas sur leur balai quand elles sont en colère ?", "reponse": "Parce qu'elles craignent de péter un plomb."},
    {"question": "Que fait une sorcière dans un parking ?", "reponse": "Elle essaye son balai !"},
    {"question": "Comment s'appelle un dinosaure qui dort ?", "reponse": "Un dino-ronfle !"},

    {"question": "Pourquoi les programmeurs préfèrent-ils le froid ?", "reponse": "Parce que sinon ils ont des bugs."},
    {"question": "Pourquoi les développeurs confondent Noël et Halloween ?", "reponse": "Parce qu'Oct 31 égale Dec 25 en code !"},
    {"question": "Combien faut-il de programmeurs pour changer une ampoule ?", "reponse": "Aucun, c'est un problème de hardware !"},
    {"question": "Quel est le meilleur langage pour un chien ?", "reponse": "Le JavaScript, parce qu'il aime les promises."},

    {"question": "Pourquoi ne faut-il pas jouer aux cartes dans la savane ?", "reponse": "Parce qu'il y a trop de guépards !"},
    {"question": "Que fait un poulet dans un micro-ondes ?", "reponse": "Il tourne en rond en se demandant ce qui lui arrive !"},
    {"question": "Que fait une vache quand elle ferme les yeux ?", "reponse": "Du lait concentré !"},
    {"question": "Qu'est-ce qu'un chat qui parle ?", "reponse": "Un cha-bavard !"},
    {"question": "Que dit un citron quand on l'embête ?", "reponse": "Tu me prends pour une poire ou quoi ?"},

    {"question": "Un touriste demande à un paysan : C'est quoi le nom de votre chien ? Le paysan répond :", "reponse": "On ne sait pas, on n'arrive pas à lui demander."},
    {"question": "Un homme dit au médecin : Docteur, j'ai mal partout où je touche. Le docteur répond :", "reponse": "C'est que vous avez le doigt cassé !"},
    {"question": "Qu'est-ce que dit une maman tomate à son fils qui traîne ?", "reponse": "Allez, ketch-up !"},
    {"question": "Que dit une maman maïs à son enfant ?", "reponse": "Je t'adore, mon pop !"},
    {"question": "Un escargot traverse la route. Un autre le regarde et dit :", "reponse": "Et bah, il est pressé celui-là !"},

    {"question": "Pourquoi les anges vont au ciel ?", "reponse": "Parce qu'ils ont la tête légère !"},
    {"question": "Comment appelle-t-on un chien qui fait du patin à glace ?", "reponse": "Un esquimau !"},
    {"question": "Pourquoi les astronautes n'ont-ils jamais faim après un voyage dans l'espace ?", "reponse": "Parce qu'ils viennent de lancer-dîner !"},
    {"question": "Quelle lettre vole dans le ciel ?", "reponse": "La lettre L... elle !"},
    {"question": "Quel est l'animal le plus rusé ?", "reponse": "Le serpent à son nez... à sonnette !"},
    {"question": "Qu'est-ce qu'un pull de luxe ?", "reponse": "Un pull-over-mouillé !"},
    {"question": "Que se dit deux chaussettes au réveil ?", "reponse": "Tiens, on s'est trouvées !"},
    {"question": "Pourquoi est-ce que les dinosaures ont disparu ?", "reponse": "Parce que le mot dinosaure existait pas encore, donc personne pouvait les appeler."},

    {"question": "Qu'est-ce qui est rouge et qui fait zzz...zzz ?", "reponse": "Une fraise qui dort !"},
    {"question": "Qu'est-ce qui est orange et qui attend ?", "reponse": "Carotte-tend."},
    {"question": "Qu'est-ce qui est vert et qui attend ?", "reponse": "Salade-tend."},
    {"question": "Qu'est-ce qui est bleu et qui flotte ?", "reponse": "Une Schtroumpf-isette."},
    {"question": "Qu'est-ce qu'un chameau sans bosses ?", "reponse": "Achmed !"},
    {"question": "Comment fait-on pleurer un bébé champignon ?", "reponse": "On lui coupe son pied !"},
]
