# blagues.py - Liste de blagues en francais (500 blagues)
# Chaque blague est un dictionnaire avec :
#   "question" : la mise en place (dite en premier)
#   "reponse"  : la chute (dite apres une petite pause)

blagues = [
    # === Qu'est-ce qui... (couleurs et actions) ===
    {"question": "Qu'est-ce qui est jaune et qui attend ?", "reponse": "Jonathan !"},
    {"question": "Qu'est-ce qui est vert et qui monte et qui descend ?", "reponse": "Un petit pois dans un ascenseur."},
    {"question": "Qu'est-ce qui est rouge et qui monte et qui descend ?", "reponse": "Une tomate dans un ascenseur."},
    {"question": "Qu'est-ce qui est jaune et qui court tres vite ?", "reponse": "Un citron presse !"},
    {"question": "Qu'est-ce qui est transparent et qui sent la carotte ?", "reponse": "Un pet de lapin."},
    {"question": "Qu'est-ce qui est petit, marron et qui grimpe aux arbres ?", "reponse": "Un marron qui a perdu son arbre."},
    {"question": "Qu'est-ce qui est vert et qui devient rouge quand on appuie sur un bouton ?", "reponse": "Une grenouille dans un mixeur."},
    {"question": "Qu'est-ce qui est jaune et qui pique ?", "reponse": "Une abeille en colere."},
    {"question": "Qu'est-ce qui est blanc et qui monte ?", "reponse": "Un idiot dans un ascenseur."},
    {"question": "Qu'est-ce qui est gris, avec une trompe et qui vole a 500 km heure ?", "reponse": "Un elephant en avion !"},
    {"question": "Qu'est-ce qui est orange et qui attend ?", "reponse": "Carotte-tend !"},
    {"question": "Qu'est-ce qui est vert et qui attend ?", "reponse": "Salade-tend !"},
    {"question": "Qu'est-ce qui est bleu et qui flotte ?", "reponse": "Une Schtroumpfette dans la piscine."},
    {"question": "Qu'est-ce qui est rouge et qui fait zzz zzz ?", "reponse": "Une fraise qui dort !"},
    {"question": "Qu'est-ce qui est rouge et mauvais pour les dents ?", "reponse": "Une brique."},
    {"question": "Qu'est-ce qui est vert et qui pousse au fond du jardin ?", "reponse": "Meme qui fait du bicross."},
    {"question": "Qu'est-ce qui est petit, noir et qui fait peur aux poissons ?", "reponse": "Le noyau de l'abricot."},
    {"question": "Qu'est-ce qui est pire que de trouver un ver dans sa pomme ?", "reponse": "En trouver la moitie."},
    {"question": "Qu'est-ce qui est marron et qui a une trompe ?", "reponse": "Un marron qui part en voyage."},
    {"question": "Qu'est-ce qui est rose et qui fait bzzz ?", "reponse": "Une cochonne electrique."},
    {"question": "Qu'est-ce qui est noir et qui vole ?", "reponse": "Un corbeau, et aussi un pickpocket de nuit."},
    {"question": "Qu'est-ce qui est petit, vert et qui grimpe ?", "reponse": "Un petit pois alpiniste."},
    {"question": "Qu'est-ce qui est jaune et qui fait tutut ?", "reponse": "Un citron dans un embouteillage."},
    {"question": "Qu'est-ce qui est violet et qui fait pschitt ?", "reponse": "Une aubergine qui a perdu son air."},
    {"question": "Qu'est-ce qui est blanc et qui descend ?", "reponse": "Un intelligent dans un ascenseur."},
    {"question": "Qu'est-ce qui est bleu et qui attend ?", "reponse": "Bleu-attend !"},
    {"question": "Qu'est-ce qui est gris et qui fait des bonds ?", "reponse": "Un souriceau sur un trampoline."},
    {"question": "Qu'est-ce qui est rond et qui fait du bruit ?", "reponse": "Un ballon qui rote."},
    {"question": "Qu'est-ce qui est plat et qui vole ?", "reponse": "Une crepe sur un tapis magique."},
    {"question": "Qu'est-ce qui est haut et qui siffle ?", "reponse": "Un arbre qui a le vertige."},

    # === Pourquoi... ===
    {"question": "Pourquoi les plongeurs plongent-ils toujours en arriere ?", "reponse": "Parce que sinon, ils tombent dans le bateau."},
    {"question": "Pourquoi les pompiers ont-ils des bretelles rouges ?", "reponse": "Pour tenir leur pantalon !"},
    {"question": "Pourquoi les canards sont-ils toujours a l'heure ?", "reponse": "Parce qu'ils sont dans l'etang !"},
    {"question": "Pourquoi les poissons detestent-ils les ordinateurs ?", "reponse": "Parce qu'ils ont peur du net !"},
    {"question": "Pourquoi les elephants ne peuvent pas monter aux arbres ?", "reponse": "Parce qu'ils n'ont pas la carte bleue."},
    {"question": "Pourquoi les girafes ont-elles un long cou ?", "reponse": "Parce qu'elles ont les pieds qui puent !"},
    {"question": "Pourquoi les moutons ne font-ils pas de bruit en rentrant chez eux ?", "reponse": "Parce qu'ils portent des chaussons."},
    {"question": "Pourquoi les vaches ferment-elles les yeux pour traire ?", "reponse": "Pour faire du lait concentre."},
    {"question": "Pourquoi les mathematiciens confondent Halloween et Noel ?", "reponse": "Parce qu'Octobre 31 egale Decembre 25 !"},
    {"question": "Pourquoi les piments rougissent ?", "reponse": "Parce qu'ils voient la salade se faire assaisonner."},
    {"question": "Pourquoi les anges vont au ciel ?", "reponse": "Parce qu'ils ont la tete legere !"},
    {"question": "Pourquoi les astronautes n'ont-ils pas faim apres un voyage ?", "reponse": "Parce qu'ils viennent de lancer-diner !"},
    {"question": "Pourquoi les dinosaures ont disparu ?", "reponse": "Parce que le mot dinosaure n'existait pas, personne ne pouvait les appeler."},
    {"question": "Pourquoi les vampires ne se marient-ils pas ?", "reponse": "Parce que le mariage, c'est pour la vie !"},
    {"question": "Pourquoi les fantomes ont-ils toujours froid ?", "reponse": "Parce qu'ils portent des draps."},
    {"question": "Pourquoi les sorcieres ne montent-elles pas sur leur balai quand elles sont enervees ?", "reponse": "Parce qu'elles craignent de peter un plomb."},
    {"question": "Pourquoi les programmeurs preferent-ils le froid ?", "reponse": "Parce que sinon ils ont des bugs."},
    {"question": "Pourquoi les poules pondent-elles des oeufs ?", "reponse": "Parce que si elles les lachaient, ils se casseraient !"},
    {"question": "Pourquoi ne faut-il pas jouer aux cartes dans la savane ?", "reponse": "Parce qu'il y a trop de guepards !"},
    {"question": "Pourquoi les Belges mettent deux cartouches dans leur fusil ?", "reponse": "Au cas ou le premier coup ferait pschitt !"},
    {"question": "Pourquoi les pingouins ne peuvent pas voler ?", "reponse": "Parce qu'ils n'ont pas de billet d'avion."},
    {"question": "Pourquoi les kangourous portent-ils leurs bebes dans une poche ?", "reponse": "Parce qu'ils ont peur qu'ils leur fassent les poches."},
    {"question": "Pourquoi les escargots ont-ils une coquille ?", "reponse": "Parce que sinon ils s'abimeraient au soleil."},
    {"question": "Pourquoi les abeilles bourdonnent ?", "reponse": "Parce qu'elles ne connaissent pas les paroles."},
    {"question": "Pourquoi les hippopotames aiment-ils l'eau ?", "reponse": "Parce qu'a l'interieur ils sont pourris."},
    {"question": "Pourquoi les chats ne vont pas a la plage ?", "reponse": "Parce qu'ils ont peur du sable dans leurs chaussons."},
    {"question": "Pourquoi les chiens tournent avant de se coucher ?", "reponse": "Pour bien faire leur nid."},
    {"question": "Pourquoi les tortues vivent-elles si longtemps ?", "reponse": "Parce qu'elles ne se pressent jamais !"},
    {"question": "Pourquoi les lions n'attaquent-ils pas les touristes ?", "reponse": "Parce qu'ils ont peur de l'indigestion."},
    {"question": "Pourquoi les zebres ont-ils des rayures ?", "reponse": "Parce que ca fait plus chic au safari."},
    {"question": "Pourquoi la mer est bleue ?", "reponse": "Parce que les poissons font blub blub !"},
    {"question": "Pourquoi les Schtroumpfs rient toujours ?", "reponse": "Parce qu'ils ont de l'herbe plein les chaussures."},
    {"question": "Pourquoi les squelettes sont-ils calmes ?", "reponse": "Parce qu'ils n'ont pas les nerfs."},
    {"question": "Pourquoi le coq chante-t-il les yeux fermes ?", "reponse": "Parce qu'il connait la chanson par coeur."},
    {"question": "Pourquoi les cyclopes ne se marient jamais ?", "reponse": "Parce qu'ils ne voient qu'une personne a la fois."},
    {"question": "Pourquoi les professeurs portent-ils des lunettes ?", "reponse": "Pour mieux voir les eleves qui dorment."},
    {"question": "Pourquoi les chauves-souris dorment la tete en bas ?", "reponse": "Parce qu'elles ont peur de se decoiffer."},
    {"question": "Pourquoi les koalas dorment tout le temps ?", "reponse": "Parce qu'ils ont un travail fatigant : rien."},
    {"question": "Pourquoi les chevaux ne portent pas de chaussures ?", "reponse": "Parce que les fers font trop de bruit sur le parquet."},
    {"question": "Pourquoi un coq a-t-il des plumes ?", "reponse": "Parce qu'avec des poils ce serait un chat."},
    {"question": "Pourquoi Batman ne va-t-il pas au restaurant ?", "reponse": "Parce qu'il prefere manger dans sa Batmobile."},

    # === Quelle est la difference... ===
    {"question": "Quelle est la difference entre un hibou et un courant d'air ?", "reponse": "Le hibou hulule, alors que le courant d'air hulule-ule !"},
    {"question": "Quelle est la difference entre un parisien et un yaourt ?", "reponse": "Au bout d'un certain temps, le yaourt devient moins aigri."},
    {"question": "Quelle est la difference entre un radiateur et un chauffage ?", "reponse": "Aucune, mais pour un radiateur on est sur !"},
    {"question": "Quelle est la difference entre une pizza et un musicien ?", "reponse": "Une pizza peut nourrir une famille de quatre."},
    {"question": "Quelle est la difference entre une gare et une salle de concert ?", "reponse": "Dans une gare, il y a marque defense de cracher."},
    {"question": "Quelle est la difference entre un elephant et un biscuit ?", "reponse": "Essaie donc de tremper un elephant dans ton cafe !"},
    {"question": "Quelle est la difference entre un crocodile et un alligator ?", "reponse": "L'un voit plus tard, l'autre voit un peu plus tot !"},
    {"question": "Quelle est la difference entre un boxeur et un enrhume ?", "reponse": "Le boxeur encaisse les coups, l'enrhume se mouche."},
    {"question": "Quelle est la difference entre un piano et un poisson ?", "reponse": "On ne peut pas accorder un poisson."},
    {"question": "Quelle est la difference entre les autoroutes et le papier toilette ?", "reponse": "Sur le papier toilette, on peut choisir de faire ses besoins ou pas."},
    {"question": "Quelle est la difference entre un chewing-gum et un elastique ?", "reponse": "Aucune, les deux collent aux fesses."},
    {"question": "Quelle est la difference entre un joueur de foot et une poule ?", "reponse": "La poule, elle, pond !"},
    {"question": "Quelle est la difference entre un baiser et une locomotive ?", "reponse": "Aucune, les deux font tchoutchou !"},
    {"question": "Quelle est la difference entre un pigeon et un banquier ?", "reponse": "Le pigeon, lui, peut encore faire une caution sur ta voiture."},
    {"question": "Quelle est la difference entre un cordonnier et un dentiste ?", "reponse": "Le cordonnier reboute les semelles, le dentiste semelle les bouches."},
    {"question": "Quelle est la difference entre un homme et un chien ?", "reponse": "Le chien, quand il est fidele, il est fidele."},
    {"question": "Quelle est la difference entre un bug et une feature ?", "reponse": "Le prix."},
    {"question": "Quelle est la difference entre une horloge et une pendule ?", "reponse": "L'horloge bat, la pendule se balance."},
    {"question": "Quelle est la difference entre un eclair et un kebab ?", "reponse": "L'eclair ne sort jamais de la patisserie."},
    {"question": "Quelle est la difference entre Louis XVI et Luke Skywalker ?", "reponse": "Luke Skywalker a un pere qui respire."},
    {"question": "Quelle est la difference entre un capitaliste et un communiste ?", "reponse": "Aucune, ils sont tous les deux pour le peuple."},
    {"question": "Quelle est la difference entre un cheveu et un poil ?", "reponse": "La couleur du coiffeur qui le tire."},
    {"question": "Quelle est la difference entre un couteau et un enfant ?", "reponse": "On peut ranger un couteau dans un tiroir."},
    {"question": "Quelle est la difference entre une comptine et une complainte ?", "reponse": "Une lettre, et deux enfants."},
    {"question": "Quelle est la difference entre un homme politique et un marteau ?", "reponse": "Le marteau tape juste."},
    {"question": "Quelle est la difference entre un monument et un politicien ?", "reponse": "Le monument, au moins, on sait ce qu'il commemore."},
    {"question": "Quelle est la difference entre un requin et un avocat ?", "reponse": "Aucune, c'est une affaire de dents."},
    {"question": "Quelle est la difference entre un bon chirurgien et un mauvais chirurgien ?", "reponse": "Le mauvais chirurgien, quand il te dit oups, c'est trop tard."},
    {"question": "Quelle est la difference entre un petard et une fusee ?", "reponse": "La fusee monte, le petard claque."},
    {"question": "Quelle est la difference entre un bon cuisinier et un mauvais cuisinier ?", "reponse": "Le mauvais, il met trop de sel."},

    # === Comment appelle-t-on... ===
    {"question": "Comment appelle-t-on un chat tombe dans un pot de peinture le jour de Noel ?", "reponse": "Un chat peint de Noel !"},
    {"question": "Comment appelle-t-on un chien sans pattes ?", "reponse": "On ne l'appelle pas, on va le chercher."},
    {"question": "Comment appelle-t-on une fourmi dans l'espace ?", "reponse": "Une cosmo-fourmi !"},
    {"question": "Comment appelle-t-on une personne qui a peur du Pere Noel ?", "reponse": "Un claustrophobe !"},
    {"question": "Comment appelle-t-on un chien qui fait du patin a glace ?", "reponse": "Un esquimau !"},
    {"question": "Comment appelle-t-on un poisson qui parle ?", "reponse": "Un perroque !"},
    {"question": "Comment appelle-t-on un rappeur chez le dentiste ?", "reponse": "Un rappeur qui fait ses molaires !"},
    {"question": "Comment appelle-t-on un champion mondial de plongee ?", "reponse": "Un homme tres profond."},
    {"question": "Comment appelle-t-on un chat qui parle ?", "reponse": "Un cha-bavard !"},
    {"question": "Comment appelle-t-on un chameau sans bosses ?", "reponse": "Achmed !"},
    {"question": "Comment appelle-t-on un dinosaure qui dort ?", "reponse": "Un dino-ronfle !"},
    {"question": "Comment appelle-t-on un chat dans le desert ?", "reponse": "Un sable-cha !"},
    {"question": "Comment appelle-t-on un chat qui fait de la magie ?", "reponse": "Un chat-mane."},
    {"question": "Comment appelle-t-on un elephant qui fait du cinema ?", "reponse": "Un elephant-tastique."},
    {"question": "Comment appelle-t-on un ours tout chaud ?", "reponse": "Un ours-in."},
    {"question": "Comment appelle-t-on un singe qui a perdu ses bananes ?", "reponse": "Un deses-pere."},
    {"question": "Comment appelle-t-on un poney qui tousse ?", "reponse": "Un petit cheval un peu malade."},
    {"question": "Comment appelle-t-on un lion avec un cerveau ?", "reponse": "Une erreur de la nature."},
    {"question": "Comment appelle-t-on un cactus chauve ?", "reponse": "Un concombre."},
    {"question": "Comment appelle-t-on une poule qui compte ?", "reponse": "Une calcoule."},
    {"question": "Comment appelle-t-on un vieux bonhomme de neige ?", "reponse": "Une flaque."},
    {"question": "Comment appelle-t-on un mec qui glisse sur de la glace ?", "reponse": "Glace-cade."},
    {"question": "Comment appelle-t-on un Japonais qui se prend pour une tarte ?", "reponse": "Sushi Tarte."},
    {"question": "Comment appelle-t-on un chinois qui pleut ?", "reponse": "Ki-pleut !"},
    {"question": "Comment appelle-t-on un militaire qui ne ferme pas sa porte ?", "reponse": "Un cas-serne."},
    {"question": "Comment appelle-t-on un zebre sans rayures ?", "reponse": "Un cheval."},
    {"question": "Comment appelle-t-on un coq qui ne chante plus ?", "reponse": "Un poulet."},
    {"question": "Comment appelle-t-on un grand-pere qui sait nager ?", "reponse": "Un papy-on."},
    {"question": "Comment appelle-t-on un chat qui traverse un champ de mais ?", "reponse": "Un pop-chat !"},
    {"question": "Comment appelle-t-on un cannibale qui mange sa mere ?", "reponse": "Un orphelin !"},

    # === Que dit / Que fait... ===
    {"question": "Que fait une fraise sur un cheval ?", "reponse": "Tagada tagada !"},
    {"question": "Que dit un oignon quand il se cogne ?", "reponse": "Aie !"},
    {"question": "Que dit un escargot quand il croise une limace ?", "reponse": "Regarde, un nudiste !"},
    {"question": "Que dit un Japonais quand on lui pique son velo ?", "reponse": "Ma-zda !"},
    {"question": "Que dit un crocodile qui fait de la politique ?", "reponse": "Je suis un homme d'Etat !"},
    {"question": "Que dit une maman guepe a sa petite guepe qui ne veut pas aller a l'ecole ?", "reponse": "Mais enfin, c'est essen-tiel !"},
    {"question": "Que dit un informaticien qui s'ennuie ?", "reponse": "C'est souris !"},
    {"question": "Que fait une vache quand elle ferme les yeux ?", "reponse": "Du lait concentre !"},
    {"question": "Que fait un poulet dans un micro-ondes ?", "reponse": "Il tourne en rond en se demandant ce qui lui arrive !"},
    {"question": "Que dit un citron quand on l'embete ?", "reponse": "Tu me prends pour une poire ou quoi ?"},
    {"question": "Que fait une sorciere dans un parking ?", "reponse": "Elle essaie son balai !"},
    {"question": "Que fait un bebe chauve-souris avant de dormir ?", "reponse": "Il fait pipi au plafond."},
    {"question": "Que dit une maman tomate a son fils qui traine ?", "reponse": "Allez, ketch-up !"},
    {"question": "Que dit une maman mais a son enfant ?", "reponse": "Je t'adore, mon pop !"},
    {"question": "Que dit un pere au tableau noir ?", "reponse": "T'as une sale craie !"},
    {"question": "Que dit un chasseur a un ours qui grimpe ?", "reponse": "Descends de la, espece de mal eleve !"},
    {"question": "Que dit une poule qui vient de pondre un oeuf ?", "reponse": "Voila qui est fait !"},
    {"question": "Que dit un boulanger quand il rate son pain ?", "reponse": "Ca miche de pres !"},
    {"question": "Que dit un cousin a un autre ?", "reponse": "On va a la piqure-nique ?"},
    {"question": "Que dit un moustique a un autre ?", "reponse": "T'as piquee qui ?"},
    {"question": "Que dit un zero a un huit ?", "reponse": "Beau ceinturon !"},
    {"question": "Que dit un asticot dans une pomme ?", "reponse": "Il fait sombre ici ! Surtout quand on ferme les yeux !"},
    {"question": "Que dit un chat qui a perdu sa voix ?", "reponse": "Miaou tout bas."},
    {"question": "Que fait un crocodile quand il a faim ?", "reponse": "Il ferme sa gueule et il croque-dile !"},
    {"question": "Que fait un boulanger en vacances ?", "reponse": "Il se la mie douce."},
    {"question": "Que fait un chien qui rencontre une poule ?", "reponse": "Rien, il est bien eleve."},
    {"question": "Que dit un petit oeuf a sa maman ?", "reponse": "Mam ! J'ai peur du coquille !"},
    {"question": "Que fait un chat avec une souris ?", "reponse": "Il joue au chat et a la souris."},
    {"question": "Que dit un boulanger a son fils ?", "reponse": "Tu es la creme de la creme !"},
    {"question": "Que dit un cure a une nonne ?", "reponse": "Vous avez l'air sainte-e-mentale !"},

    # === Monsieur et Madame... ===
    {"question": "Monsieur et Madame Terieur ont une fille. Comment s'appelle-t-elle ?", "reponse": "Alex ! Alex Terieur !"},
    {"question": "Monsieur et Madame Terieur ont un fils. Comment s'appelle-t-il ?", "reponse": "Alain ! Alain Terieur !"},
    {"question": "Monsieur et Madame Ficelle ont un fils. Comment s'appelle-t-il ?", "reponse": "Jean ! Jean Ficelle !"},
    {"question": "Monsieur et Madame Achere ont une fille. Comment s'appelle-t-elle ?", "reponse": "Sophie ! Sophie Achere !"},
    {"question": "Monsieur et Madame Oiseau ont un fils. Comment s'appelle-t-il ?", "reponse": "Lou ! Lou Oiseau !"},
    {"question": "Monsieur et Madame Uzi ont un fils. Comment s'appelle-t-il ?", "reponse": "Jacques ! Jacques Uzi !"},
    {"question": "Monsieur et Madame Pon ont une fille. Comment s'appelle-t-elle ?", "reponse": "Nathalie ! Nathalie Pon !"},
    {"question": "Monsieur et Madame Ginal ont un fils. Comment s'appelle-t-il ?", "reponse": "Auguste ! Auguste Ginal !"},
    {"question": "Monsieur et Madame Sapatro ont un fils. Comment s'appelle-t-il ?", "reponse": "Jean ! Jean Sapatro !"},
    {"question": "Monsieur et Madame Kipik ont un fils. Comment s'appelle-t-il ?", "reponse": "Laurent ! Laurent Kipik !"},
    {"question": "Monsieur et Madame Zeble ont un fils. Comment s'appelle-t-il ?", "reponse": "Paul ! Paul Zeble !"},
    {"question": "Monsieur et Madame Plantation ont une fille. Comment s'appelle-t-elle ?", "reponse": "Camille ! Camille Plantation !"},
    {"question": "Monsieur et Madame Kable ont une fille. Comment s'appelle-t-elle ?", "reponse": "Nadia ! Nadia Kable !"},
    {"question": "Monsieur et Madame Matinable ont un fils. Comment s'appelle-t-il ?", "reponse": "Ali ! Ali Matinable !"},
    {"question": "Monsieur et Madame Nelle ont un fils. Comment s'appelle-t-il ?", "reponse": "Lionel ! Lionel Nelle !"},
    {"question": "Monsieur et Madame Nelafete ont un fils. Comment s'appelle-t-il ?", "reponse": "Ben ! Ben Nelafete !"},
    {"question": "Monsieur et Madame Grossier ont une fille. Comment s'appelle-t-elle ?", "reponse": "Marie ! Marie Grossier !"},
    {"question": "Monsieur et Madame Dupin ont une fille. Comment s'appelle-t-elle ?", "reponse": "Melanie ! Melanie Dupin !"},
    {"question": "Monsieur et Madame Crehon ont un fils. Comment s'appelle-t-il ?", "reponse": "Sam ! Sam Crehon !"},
    {"question": "Monsieur et Madame Tu ont une fille. Comment s'appelle-t-elle ?", "reponse": "Clara ! Clara Tu !"},
    {"question": "Monsieur et Madame Itelarchipel ont une fille. Comment s'appelle-t-elle ?", "reponse": "Iris ! Iris Itelarchipel !"},
    {"question": "Monsieur et Madame Odeur ont un fils. Comment s'appelle-t-il ?", "reponse": "Mal ! Mal Odeur !"},
    {"question": "Monsieur et Madame Zik ont un fils. Comment s'appelle-t-il ?", "reponse": "Tommy ! Tommy Zik !"},
    {"question": "Monsieur et Madame Proviste ont un fils. Comment s'appelle-t-il ?", "reponse": "Alain ! Alain Proviste !"},
    {"question": "Monsieur et Madame Zailecoude ont un fils. Comment s'appelle-t-il ?", "reponse": "Jean ! Jean Zailecoude !"},
    {"question": "Monsieur et Madame Coba ont une fille. Comment s'appelle-t-elle ?", "reponse": "Laura ! Laura Coba !"},
    {"question": "Monsieur et Madame Diam ont un fils. Comment s'appelle-t-il ?", "reponse": "Tom ! Tom Diam !"},
    {"question": "Monsieur et Madame German ont une fille. Comment s'appelle-t-elle ?", "reponse": "Sandra ! Sandra German !"},
    {"question": "Monsieur et Madame Ciecroche ont un fils. Comment s'appelle-t-il ?", "reponse": "Nate ! Nate Ciecroche !"},
    {"question": "Monsieur et Madame Eudelavi ont une fille. Comment s'appelle-t-elle ?", "reponse": "Joyce ! Joyce Eudelavi !"},
    {"question": "Monsieur et Madame Hertein ont un fils. Comment s'appelle-t-il ?", "reponse": "Albert ! Albert Hertein !"},
    {"question": "Monsieur et Madame Nerien ont un fils. Comment s'appelle-t-il ?", "reponse": "Sam ! Sam Nerien !"},
    {"question": "Monsieur et Madame Petit ont un fils. Comment s'appelle-t-il ?", "reponse": "Jean ! Jean Petit !"},
    {"question": "Monsieur et Madame Drolle ont une fille. Comment s'appelle-t-elle ?", "reponse": "Maud ! Maud Drolle !"},
    {"question": "Monsieur et Madame Tel ont une fille. Comment s'appelle-t-elle ?", "reponse": "Estelle ! Estelle Tel !"},
    {"question": "Monsieur et Madame Ficologue ont un fils. Comment s'appelle-t-il ?", "reponse": "Benoit ! Benoit Ficologue !"},
    {"question": "Monsieur et Madame Onche ont une fille. Comment s'appelle-t-elle ?", "reponse": "Laetitia ! Laetitia Onche !"},
    {"question": "Monsieur et Madame Lepiroul ont un fils. Comment s'appelle-t-il ?", "reponse": "Ali ! Ali Lepiroul !"},
    {"question": "Monsieur et Madame Bour ont un fils. Comment s'appelle-t-il ?", "reponse": "Sam ! Sam Bour !"},
    {"question": "Monsieur et Madame Bour ont une fille. Comment s'appelle-t-elle ?", "reponse": "Sandra ! Sandra Bour !"},
    {"question": "Monsieur et Madame Diou ont une fille. Comment s'appelle-t-elle ?", "reponse": "Marie ! Marie Diou !"},
    {"question": "Monsieur et Madame Beille ont une fille. Comment s'appelle-t-elle ?", "reponse": "Anne ! Anne Beille !"},
    {"question": "Monsieur et Madame Flageolet ont un fils. Comment s'appelle-t-il ?", "reponse": "Jean ! Jean Flageolet !"},
    {"question": "Monsieur et Madame Deneige ont un fils. Comment s'appelle-t-il ?", "reponse": "Kim ! Kim Deneige !"},
    {"question": "Monsieur et Madame Pactepote ont un fils. Comment s'appelle-t-il ?", "reponse": "Sam ! Sam Pactepote !"},
    {"question": "Monsieur et Madame Hontay ont une fille. Comment s'appelle-t-elle ?", "reponse": "Marianne ! Marianne Hontay !"},
    {"question": "Monsieur et Madame Housseure ont un fils. Comment s'appelle-t-il ?", "reponse": "Thom ! Thom Housseure !"},
    {"question": "Monsieur et Madame Lufrai ont un fils. Comment s'appelle-t-il ?", "reponse": "Raoul ! Raoul Lufrai !"},
    {"question": "Monsieur et Madame Sique ont un fils. Comment s'appelle-t-il ?", "reponse": "Tom ! Tom Sique !"},
    {"question": "Monsieur et Madame Mur ont une fille. Comment s'appelle-t-elle ?", "reponse": "Armelle ! Armelle Mur !"},
    {"question": "Monsieur et Madame Bobine ont un fils. Comment s'appelle-t-il ?", "reponse": "Eric ! Eric Bobine !"},
    {"question": "Monsieur et Madame Zeul ont un fils. Comment s'appelle-t-il ?", "reponse": "Sam ! Sam Zeul !"},
    {"question": "Monsieur et Madame Zeble ont une fille. Comment s'appelle-t-elle ?", "reponse": "Pauline ! Pauline Zeble !"},
    {"question": "Monsieur et Madame Lerance ont un fils. Comment s'appelle-t-il ?", "reponse": "Tom ! Tom Lerance !"},
    {"question": "Monsieur et Madame Akissejpa ont un fils. Comment s'appelle-t-il ?", "reponse": "Jean ! Jean Akissejpa !"},

    # === Toto ===
    {"question": "La maitresse demande a Toto de conjuguer marcher. Toto repond :", "reponse": "Je marche, tu marches... Plus vite Toto ! Je cours, tu cours..."},
    {"question": "Maman, a l'ecole on m'appelle Lucky Luke ! La mere repond :", "reponse": "Dis-leur d'arreter Toto, depeche ! Plus vite que son ombre !"},
    {"question": "Toto, pourquoi es-tu en retard a l'ecole ? Toto repond :", "reponse": "J'ai reve d'un match de foot madame, et il y a eu des prolongations !"},
    {"question": "Toto, pourquoi as-tu zero en geographie ?", "reponse": "Vous avez dit que la Terre tournait, j'ai attendu que ma copie revienne !"},
    {"question": "La maitresse demande a Toto d'epeler cheval. Toto repond :", "reponse": "Je peux pas madame, j'ai peur qu'il me donne un coup de sabot."},
    {"question": "Toto, pourquoi tu bois la tasse a la piscine ?", "reponse": "Parce que j'ai soif madame !"},
    {"question": "Toto, fais-moi une phrase avec hydrogene et zinc. Toto dit :", "reponse": "Mon papa m'a dit j'hydrogene mon zinc sur le buffet."},
    {"question": "Toto, ou se trouve l'Espagne ?", "reponse": "Page 34 madame, en bas a droite !"},
    {"question": "Toto, qu'est-ce que l'inertie ?", "reponse": "C'est quand maman me dit de me bouger et que je ne le fais pas."},
    {"question": "Toto, pourquoi tu souris en faisant tes devoirs ?", "reponse": "Parce que j'aime la surprise de voir les notes rouges apres."},
    {"question": "Toto, cite-moi un liquide qui ne gele jamais.", "reponse": "L'eau bouillante, madame."},
    {"question": "Toto, qui a peint La Joconde ?", "reponse": "Pas moi madame !"},
    {"question": "Toto, combien font 2 plus 2 ?", "reponse": "C'est combien que vous avez deja madame ?"},
    {"question": "Toto, pourquoi as-tu un oeuf sur la tete ?", "reponse": "Parce que tu m'as dit de faire une omelette avec ce que j'avais en tete."},
    {"question": "Toto, comment s'appelle ton grand-pere ?", "reponse": "Comme moi madame, mais en plus vieux."},
    {"question": "Toto, pourquoi tu manges avec les doigts ?", "reponse": "Parce que j'ai perdu ma fourchette dans la soupe."},
    {"question": "Toto, ou sont les Pyrenees ?", "reponse": "Entre la France et l'Espagne, madame. Elles bougent pas souvent."},
    {"question": "Toto, qu'est-ce qu'une ile ?", "reponse": "C'est un truc qui flotte et qui a pas de pattes."},
    {"question": "Toto, cite un animal herbivore.", "reponse": "La vache. Elle mange de l'herbe, et apres elle sort du lait. C'est magique."},
    {"question": "Toto, pourquoi tu ris en classe ?", "reponse": "Parce que vous m'avez dit de sourire a la vie, madame."},
    {"question": "Toto, explique la gravite.", "reponse": "C'est quand mon ballon tombe dans le jardin du voisin."},
    {"question": "Toto, quel est le pluriel de cheval ?", "reponse": "Chevaux ! Et au singulier c'est vache, madame."},
    {"question": "Toto, qu'est-ce que l'economie ?", "reponse": "C'est quand papa dit qu'il n'y a plus d'argent."},
    {"question": "Toto, tu as rendu une copie blanche !", "reponse": "Grands esprits se rencontrent, madame. La votre aussi."},
    {"question": "Toto, quel est le contraire de froid ?", "reponse": "Pas froid, madame."},
    {"question": "Toto, qu'est-ce que l'histoire ?", "reponse": "C'est quand on raconte quelque chose qui est deja fini."},
    {"question": "Toto, que veut dire SOS ?", "reponse": "Sauvez notre Toto, madame !"},
    {"question": "Toto, as-tu un surnom a l'ecole ?", "reponse": "Oui, les copains m'appellent Wikipedia : faux et toujours modifie."},
    {"question": "Toto, tu es encore en retard !", "reponse": "Oui, mais je suis arrive avant mes camarades absents."},
    {"question": "Toto, tu parles trop en classe !", "reponse": "C'est genetique, papa est homme politique."},

    # === Comble pour un metier ===
    {"question": "Quel est le comble pour un electricien ?", "reponse": "De ne pas etre au courant."},
    {"question": "Quel est le comble pour un jardinier ?", "reponse": "Raconter des salades."},
    {"question": "Quel est le comble pour un boulanger ?", "reponse": "Ne pas etre dans son petrin."},
    {"question": "Quel est le comble pour un menteur ?", "reponse": "Avoir un accent vrai."},
    {"question": "Quel est le comble pour un magicien ?", "reponse": "Se faire disparaitre sans le faire expres."},
    {"question": "Quel est le comble pour un cordonnier ?", "reponse": "Mourir de faim avec toutes ses semelles !"},
    {"question": "Quel est le comble pour un marin ?", "reponse": "Avoir le mal de mer en regardant un documentaire."},
    {"question": "Quel est le comble pour un dentiste ?", "reponse": "Mentir sans montrer ses dents."},
    {"question": "Quel est le comble pour un astronome ?", "reponse": "Voir 36 chandelles."},
    {"question": "Quel est le comble pour un chauffeur de taxi ?", "reponse": "Ne pas voir ou il va."},
    {"question": "Quel est le comble pour un facteur ?", "reponse": "Perdre la lettre de son prenom."},
    {"question": "Quel est le comble pour un pompier ?", "reponse": "Etre en feu."},
    {"question": "Quel est le comble pour un plongeur ?", "reponse": "Couler a pic."},
    {"question": "Quel est le comble pour un boucher ?", "reponse": "Avoir un tendre amour."},
    {"question": "Quel est le comble pour un musicien ?", "reponse": "Perdre la note."},
    {"question": "Quel est le comble pour un coiffeur ?", "reponse": "Se faire raser."},
    {"question": "Quel est le comble pour un pompier ?", "reponse": "Avoir une extinction de voix."},
    {"question": "Quel est le comble pour un instituteur ?", "reponse": "Perdre sa classe."},
    {"question": "Quel est le comble pour un cuisinier ?", "reponse": "Perdre la recette."},
    {"question": "Quel est le comble pour un chanteur ?", "reponse": "Perdre sa voix dans la rue."},
    {"question": "Quel est le comble pour un detective ?", "reponse": "Ne pas trouver son chemin."},
    {"question": "Quel est le comble pour un optometriste ?", "reponse": "Ne pas voir venir."},
    {"question": "Quel est le comble pour un boxeur ?", "reponse": "Avoir le coeur sur la main."},
    {"question": "Quel est le comble pour un pecheur ?", "reponse": "Tomber dans un panneau."},
    {"question": "Quel est le comble pour un agent de police ?", "reponse": "Se faire embarquer dans une histoire."},
    {"question": "Quel est le comble pour un ecrivain ?", "reponse": "Perdre le fil."},
    {"question": "Quel est le comble pour un horloger ?", "reponse": "Ne pas avoir le temps."},
    {"question": "Quel est le comble pour un pharmacien ?", "reponse": "Avoir une goutte au nez."},
    {"question": "Quel est le comble pour un menuisier ?", "reponse": "Avoir une planche a la place du cerveau."},
    {"question": "Quel est le comble pour un prof de maths ?", "reponse": "Perdre ses moyens."},

    # === Quel est le... ===
    {"question": "Quel est le sport le plus silencieux ?", "reponse": "Le para-chuuut !"},
    {"question": "Quel est le sport le plus fruite ?", "reponse": "La boxe, parce qu'on met des peches !"},
    {"question": "Quel est le fruit le plus prefere du prof ?", "reponse": "La reine-claude."},
    {"question": "Quel est le fruit que l'on trouve dans toutes les maisons ?", "reponse": "La coing-cuisine."},
    {"question": "Quel est le legume prefere du paresseux ?", "reponse": "Le haricot flamby."},
    {"question": "Quel est le meilleur langage pour un chien ?", "reponse": "Le JavaScript, parce qu'il aime les promises."},
    {"question": "Quel est l'animal le plus rapide de l'eau ?", "reponse": "Le sol-dat, il court sur l'eau."},
    {"question": "Quel est l'animal qui ne s'essuie pas apres manger ?", "reponse": "Le sanglier, il a une hure !"},
    {"question": "Quel est l'animal le plus rapide du monde ?", "reponse": "Le pou, parce qu'il est toujours en tete."},
    {"question": "Quel est le comble du jardinier ?", "reponse": "Ne pas savoir semer la panique."},
    {"question": "Quelle lettre vole dans le ciel ?", "reponse": "La lettre L. Elle !"},
    {"question": "Quel est l'animal le plus rusee ?", "reponse": "Le serpent a sonnette."},
    {"question": "Quel est le fruit qui ne boit jamais ?", "reponse": "La figue seche."},
    {"question": "Quel est le meilleur pays pour les voitures ?", "reponse": "Le Capot-vert."},
    {"question": "Quel est le meilleur ami du dictionnaire ?", "reponse": "Le cahier, parce qu'il sait tout."},
    {"question": "Quel est le pire voisin du musicien ?", "reponse": "Le batteur avec des insomnies."},
    {"question": "Quel est le meilleur sport du matin ?", "reponse": "Le saute-au-lit."},
    {"question": "Quel est le pire ennemi du chewing-gum ?", "reponse": "La chaussure chaude."},
    {"question": "Quel est le plus grand ennemi du requin ?", "reponse": "Le requin qui a mange trop."},
    {"question": "Quel est le signe astrologique des poissons ?", "reponse": "Aquarium ascendant bocal."},

    # === Blagues courtes ===
    {"question": "Un homme entre dans un cafe.", "reponse": "Plouf !"},
    {"question": "Un squelette entre dans un bar et commande :", "reponse": "Une biere et une serpilliere."},
    {"question": "Deux cacahuetes marchent dans la rue. L'une se fait agresser :", "reponse": "Cacahuete assaillie !"},
    {"question": "Deux baguettes entrent dans une boulangerie. Laquelle parle en premier ?", "reponse": "Aucune, les baguettes ne parlent pas !"},
    {"question": "Un zero rencontre un huit :", "reponse": "Hey, t'es bien sape avec ta ceinture !"},
    {"question": "Deux asticots sont dans une pomme. L'un dit :", "reponse": "Il fait sombre ici ! Oui, surtout quand on ferme les yeux !"},
    {"question": "Deux poissons dans un bocal. L'un dit :", "reponse": "Tu sais conduire toi ? Non, j'ai pas le permis !"},
    {"question": "Une vache coule. Qu'est-ce qu'on dit ?", "reponse": "Vache alors !"},
    {"question": "Un chat tombe dans une piscine.", "reponse": "C'est un chat-mouille."},
    {"question": "Un cheval entre dans un bar. Le barman demande :", "reponse": "Tu fais une tete de six pieds de long !"},
    {"question": "Un champignon entre dans un bar. Le barman dit :", "reponse": "Desole, on ne sert pas de champignon ! Pourquoi ? Je suis pourtant sympa !"},
    {"question": "Qu'est-ce qui voyage autour du monde en restant dans son coin ?", "reponse": "Un timbre-poste."},
    {"question": "Qu'est-ce qui pique sans etre une abeille ?", "reponse": "Un voleur."},
    {"question": "Qu'est-ce qu'une chauve-souris ?", "reponse": "Un rongeur qui a perdu ses cheveux."},
    {"question": "Qu'est-ce qu'un pull de luxe ?", "reponse": "Un pull-over-mouille !"},
    {"question": "Que se disent deux chaussettes au reveil ?", "reponse": "Tiens, on s'est trouvees !"},
    {"question": "Un touriste demande au paysan : le nom de votre chien ?", "reponse": "On ne sait pas, on n'arrive pas a lui demander."},
    {"question": "Un homme dit au medecin : j'ai mal partout ou je touche.", "reponse": "C'est que vous avez le doigt casse !"},
    {"question": "Un escargot traverse la route. Un autre :", "reponse": "Eh bah, il est presse celui-la !"},
    {"question": "Un pere Noel qui se moque d'un autre :", "reponse": "Ho ho ho ridicule !"},
    {"question": "Un livre ouvert tombe. On l'appelle comment ?", "reponse": "Un livre allonge."},
    {"question": "Une voiture en colere devient quoi ?", "reponse": "Un rap-our."},
    {"question": "Un gateau dans un lit devient quoi ?", "reponse": "Un baba au rhum-lit."},
    {"question": "Un caillou qui marche, c'est quoi ?", "reponse": "Un roc-ambole."},
    {"question": "Une peche qui boude ?", "reponse": "Une peche boudeuse !"},
    {"question": "Un hibou qui hulule tres fort ?", "reponse": "Un hibou-ste."},
    {"question": "Un fantome qui parle doucement ?", "reponse": "Un fant-om."},
    {"question": "Un avocat qui mange un avocat ?", "reponse": "Un double pleonasme."},
    {"question": "Un livre qui fait peur ?", "reponse": "Un livre a fris-son."},
    {"question": "Un canard qui grogne ?", "reponse": "Un ca-nard mecontent."},
    {"question": "Un pingouin sur une plage ?", "reponse": "Un oiseau perdu."},
    {"question": "Une grenouille au cinema ?", "reponse": "Une gre-nouille du 7e art."},
    {"question": "Une patate qui danse ?", "reponse": "Une purée soiree."},
    {"question": "Un oeuf au chapeau ?", "reponse": "Un oeuf-stylé."},
    {"question": "Une abeille au concert ?", "reponse": "Une abeille choriste."},
    {"question": "Un rat qui fait du ski ?", "reponse": "Un ra-pide."},
    {"question": "Un elephant qui fait du trapeze ?", "reponse": "Un cirque en danger."},
    {"question": "Un chat qui joue aux echecs ?", "reponse": "Un chat-champion."},
    {"question": "Un dragon qui fait un barbecue ?", "reponse": "Un dragon-grill."},
    {"question": "Un pere qui mange son fils ?", "reponse": "Un pere-vers."},
    {"question": "Un cochon qui se parfume ?", "reponse": "Un porc-coquet."},
    {"question": "Une tortue qui court ?", "reponse": "Une illusion d'optique."},
    {"question": "Une carotte qui pleure ?", "reponse": "Une carotte larmoyante."},
    {"question": "Un loup qui perd ses dents ?", "reponse": "Un loupe-dent."},
    {"question": "Un poisson-chat sans moustache ?", "reponse": "Juste un poisson."},
    {"question": "Un kangourou chez le dentiste ?", "reponse": "Un kan-gour-ou-mal."},
    {"question": "Une mouche qui fait du surf ?", "reponse": "Une mouche a maree."},
    {"question": "Un vers qui aime la pluie ?", "reponse": "Un vers luisant."},
    {"question": "Un chien qui etudie ?", "reponse": "Un labrador-deux-savant."},
    {"question": "Une fourmi qui voyage ?", "reponse": "Une mondo-fourmi."},

    # === Informatique ===
    {"question": "Combien faut-il de programmeurs pour changer une ampoule ?", "reponse": "Aucun, c'est un probleme de hardware !"},
    {"question": "Comment reconnait-on un informaticien deprime ?", "reponse": "Il regarde fixement ses chaussures. Heureux, il regarde les votres."},
    {"question": "Pourquoi les developpeurs adorent Halloween ?", "reponse": "Parce qu'Octobre 31 egale Decembre 25 en code !"},
    {"question": "Pourquoi les programmeurs n'aiment-ils pas la nature ?", "reponse": "Il y a trop de bugs."},
    {"question": "Que dit un serveur web qui a trop bu ?", "reponse": "Erreur 500 !"},
    {"question": "Pourquoi le cookie est-il triste ?", "reponse": "Parce que sa mere etait au four."},
    {"question": "Que fait un informaticien chez le medecin ?", "reponse": "Il attend un reboot."},
    {"question": "Comment un developpeur prend-il sa douche ?", "reponse": "Il se rince en boucle."},
    {"question": "Un geek entre dans un bar... et demande :", "reponse": "Avez-vous du wifi ?"},
    {"question": "Pourquoi le Python rit-il tout le temps ?", "reponse": "Parce qu'il a un bon interprete."},
    {"question": "Que dit un bug a un autre bug ?", "reponse": "On se retrouve en production !"},
    {"question": "Pourquoi un geek emmene-t-il une echelle au restaurant ?", "reponse": "Parce qu'il veut monter de niveau."},
    {"question": "Que fait un serveur quand il est fatigue ?", "reponse": "Il prend une pause SQL."},
    {"question": "Pourquoi le bit est-il fatigue ?", "reponse": "Parce qu'il a passe la journee entre zero et un."},
    {"question": "Pourquoi le developpeur Java prefere-t-il le cafe ?", "reponse": "Parce qu'il adore les beans."},
    {"question": "Que fait un informaticien le week-end ?", "reponse": "Il se deconnecte... de la vraie vie."},
    {"question": "Pourquoi le CSS pleure ?", "reponse": "Parce qu'on ne l'aligne jamais correctement."},
    {"question": "Que dit le cable Ethernet a son collegue ?", "reponse": "T'es bien connecte aujourd'hui !"},
    {"question": "Pourquoi le disque dur va-t-il en therapie ?", "reponse": "Il a trop de fragments emotionnels."},
    {"question": "Un programmeur se noie dans une piscine :", "reponse": "Il hurle F1 F1 !"},

    # === Medecin ===
    {"question": "Docteur, je me prends pour un rideau. Le docteur :", "reponse": "Allez, tirez-vous !"},
    {"question": "Docteur, j'ai l'impression d'etre une montre. Le docteur :", "reponse": "Vous faites des complexes du temps."},
    {"question": "Docteur, je me prends pour un paquet de cartes. Le docteur :", "reponse": "Asseyez-vous, je vais vous les battre."},
    {"question": "Docteur, quand je me leve le matin, je suis tout etourdi. Le docteur :", "reponse": "Levez-vous le soir !"},
    {"question": "Docteur, je perds la memoire. Depuis quand ?", "reponse": "Depuis quand quoi ?"},
    {"question": "Docteur, je me prends pour un chien. Depuis quand ?", "reponse": "Depuis que je suis petit chiot !"},
    {"question": "Docteur, ma femme se prend pour un ascenseur. Le docteur :", "reponse": "Faites-la monter ! Non, je ne peux pas, elle ne s'arrete qu'au rez-de-chaussee."},
    {"question": "Docteur, j'ai une laitue coincee dans l'oreille. Le docteur :", "reponse": "Ce n'est que la partie emergee du jardin."},
    {"question": "Docteur, j'ai du mal a dormir. Le docteur :", "reponse": "Dormez sur un bord du lit, vous tomberez dans les bras de Morphee."},
    {"question": "Docteur, mon mari se prend pour une poule. Ca dure depuis quand ?", "reponse": "Depuis trois ans. Pourquoi ne l'emmenez-vous pas plus tot ? On avait besoin des oeufs !"},
    {"question": "Docteur, j'ai peur des chauves-souris. Le docteur :", "reponse": "C'est chiroptero-nevrose."},
    {"question": "Docteur, j'ai une maladie de peau. Le docteur :", "reponse": "Sautez la, derma-tologiquement parlant."},
    {"question": "Docteur, j'ai une carie. Le docteur :", "reponse": "Allons bon, ca ne mache pas de paroles."},
    {"question": "Docteur, je vois des araignees partout. Allongez-vous...", "reponse": "Pas sur moi, je vous en supplie !"},
    {"question": "Docteur, j'ai avale un os. Le docteur :", "reponse": "Vous voila dans l'ossification."},
    {"question": "Docteur, j'ai un probleme d'audition.", "reponse": "Repetez un peu ?"},
    {"question": "Docteur, j'ai toujours froid. Le docteur :", "reponse": "C'est que vous manquez de calories dans la tete."},
    {"question": "Docteur, je suis stressee. Le docteur :", "reponse": "Essayez de ne plus penser aux echeances... ah oui, d'ailleurs, voici ma note."},
    {"question": "Docteur, j'ai mal a la gorge. Depuis quand ?", "reponse": "Depuis que j'avale des oui oui."},
    {"question": "Docteur, j'ai mal au dos. Le docteur :", "reponse": "C'est l'age qui me casse."},

    # === Animaux ===
    {"question": "Que dit un chat qui a soif ?", "reponse": "J'ai soif miaou j'ai soif !"},
    {"question": "Que fait un crocodile quand il pleut ?", "reponse": "Il est mouille."},
    {"question": "Comment un chien se presente-t-il ?", "reponse": "Enchante, woof !"},
    {"question": "Quel est le contraire d'un chat noir ?", "reponse": "Un chat pas noir."},
    {"question": "Pourquoi l'elephant met ses chaussures rouges dans le frigo ?", "reponse": "Pour surprendre le jambon !"},
    {"question": "Pourquoi met-il des chaussures jaunes dans le frigo ?", "reponse": "Parce que la chaussure rouge s'y sentait seule."},
    {"question": "Comment un elephant monte-t-il sur un arbre ?", "reponse": "Il s'assoit sur un gland et attend que l'arbre pousse."},
    {"question": "Pourquoi le chien aboie-t-il ?", "reponse": "Parce qu'il n'a pas lu le panneau silence."},
    {"question": "Que fait un chat avec une calculatrice ?", "reponse": "Il compte-mpteur."},
    {"question": "Pourquoi les pingouins vivent-ils au pole sud ?", "reponse": "Parce qu'au nord il y a deja les ours."},
    {"question": "Que fait un chameau dans le Sahara ?", "reponse": "Il fait le chameau."},
    {"question": "Pourquoi les taupes sont-elles aveugles ?", "reponse": "Parce que sous terre, il n'y a pas d'opticien."},
    {"question": "Pourquoi les fourmis travaillent-elles tout le temps ?", "reponse": "Parce qu'elles n'ont pas de canape."},
    {"question": "Comment s'appelle la maman de la licorne ?", "reponse": "Li-conne."},
    {"question": "Pourquoi les poissons ne jouent-ils pas au tennis ?", "reponse": "Parce qu'ils ont peur du filet !"},
    {"question": "Que fait un escargot quand il fait froid ?", "reponse": "Rien, il est au ralenti."},
    {"question": "Pourquoi les vers ne portent pas de lunettes ?", "reponse": "Parce qu'ils n'ont pas d'oreilles pour les tenir."},
    {"question": "Pourquoi les cochons adorent la boue ?", "reponse": "C'est leur spa prefere."},
    {"question": "Que dit un caneton a sa mere ?", "reponse": "Eh bah, tu me couves ?"},
    {"question": "Pourquoi les lions mangent-ils la viande crue ?", "reponse": "Parce qu'ils ne savent pas cuisiner."},
    {"question": "Pourquoi le hibou est-il sage ?", "reponse": "Parce qu'il passe ses nuits a reflechir."},
    {"question": "Que fait un castor qui travaille trop ?", "reponse": "Il fait un burrog-out."},
    {"question": "Pourquoi les moutons ne font pas de skate ?", "reponse": "Parce qu'ils glissent deja sur leur laine."},
    {"question": "Pourquoi la poule traverse la route ?", "reponse": "Pour aller de l'autre cote."},
    {"question": "Pourquoi les araignees sont-elles bonnes en Internet ?", "reponse": "Parce qu'elles tissent leur web."},
    {"question": "Pourquoi les ecureuils ont-ils la queue touffue ?", "reponse": "Pour faire peur aux courants d'air."},
    {"question": "Que fait un dauphin qui s'ennuie ?", "reponse": "Il fait des bulles de reflexion."},
    {"question": "Pourquoi les hippocampes nagent-ils droit ?", "reponse": "Parce qu'ils portent des lunettes."},
    {"question": "Que dit un caneton triste ?", "reponse": "Je suis abattu."},
    {"question": "Pourquoi les flamants roses se tiennent sur une patte ?", "reponse": "Parce que s'ils levaient l'autre, ils tomberaient."},

    # === Nourriture ===
    {"question": "Quel fromage adore le tennis ?", "reponse": "Le cantal, toujours pret pour un set."},
    {"question": "Pourquoi le pain ne parle pas ?", "reponse": "Parce qu'il a la mie coincee."},
    {"question": "Que dit un croissant a une baguette ?", "reponse": "On se leve tot tous les deux."},
    {"question": "Quel est le legume le plus bavard ?", "reponse": "Le navet, il rabache."},
    {"question": "Que fait un yaourt au supermarche ?", "reponse": "Il fait la queue."},
    {"question": "Pourquoi les oeufs detestent les blagues ?", "reponse": "Ils se fendent trop facilement."},
    {"question": "Que dit un pain au chocolat a un chocolatine ?", "reponse": "Toi et moi, on sera toujours ennemis."},
    {"question": "Pourquoi le sel pleure-t-il ?", "reponse": "Parce qu'il est toujours mis de cote."},
    {"question": "Que fait une brique de lait triste ?", "reponse": "Elle verse des larmes de lait concentre."},
    {"question": "Que dit le fromage au jambon ?", "reponse": "Ensemble, on est parfait."},
    {"question": "Quel gateau travaille dans un bureau ?", "reponse": "Le financier."},
    {"question": "Pourquoi la pomme de terre est-elle timide ?", "reponse": "Parce qu'elle a toujours les yeux baisses."},
    {"question": "Pourquoi le concombre est-il cool ?", "reponse": "Parce qu'il reste froid meme sous pression."},
    {"question": "Que fait le chocolat au cafe ?", "reponse": "Il fond d'amour."},
    {"question": "Que dit une carotte a son ami navet ?", "reponse": "On est du meme panier !"},
    {"question": "Que fait une pizza en vacances ?", "reponse": "Elle se fait dorer la pate."},
    {"question": "Pourquoi les frites sont-elles sociables ?", "reponse": "Parce qu'elles sortent toujours en groupe."},
    {"question": "Que se disent deux baguettes ?", "reponse": "On a le meme petrin."},
    {"question": "Pourquoi le sucre est-il romantique ?", "reponse": "Il fond pour un rien."},
    {"question": "Que dit une cerise triste ?", "reponse": "Mon pere est un noyau dur."},

    # === Belges / Suisses / Francais ===
    {"question": "Un Francais et un Belge dans un avion. Le Francais demande : On va ou ?", "reponse": "Je sais pas, je suis pas le pilote."},
    {"question": "Comment reconnait-on un Belge au supermarche ?", "reponse": "C'est celui qui souffle dans les caddies pour enlever la neige... en ete."},
    {"question": "Pourquoi les Suisses ont-ils trop de couteaux ?", "reponse": "Parce qu'ils sont tres pointus."},
    {"question": "Un Belge se promene avec un parapluie ouvert. On lui demande pourquoi :", "reponse": "C'est au cas ou il se mettrait a pleuvoir. Il y a nuage !"},
    {"question": "Pourquoi les Belges mettent leur montre dans le frigo ?", "reponse": "Pour avoir l'heure d'ete."},
    {"question": "Un touriste demande : quelle est la capitale de la Belgique ?", "reponse": "Je sais pas, demande a un Belge. Bruxelles ! J'allais le dire !"},
    {"question": "Comment un Belge se repere-t-il en foret ?", "reponse": "Il suit les panneaux, meme les panneaux solaires."},
    {"question": "Pourquoi un Suisse garde-t-il sa montre meme dans son bain ?", "reponse": "Pour voir si le temps s'ecoule aussi vite sous l'eau."},
    {"question": "Un Francais, un Belge et un Italien commandent au restaurant. Le Belge dit :", "reponse": "Moi je prends la meme chose que les deux autres, comme ca on gagne du temps."},
    {"question": "Pourquoi les Francais se croient le centre du monde ?", "reponse": "Parce qu'ils y sont, sur leurs cartes !"},

    # === Fins / divers ===
    {"question": "Comment fait-on pleurer un bebe champignon ?", "reponse": "On lui coupe son pied !"},
    {"question": "Pourquoi les cyclistes s'accrochent-ils ?", "reponse": "Parce qu'ils sont toujours sur le derriere de quelqu'un."},
    {"question": "Pourquoi Adam et Eve n'avaient pas de nombril ?", "reponse": "Parce qu'ils n'etaient pas nes sous la couette."},
    {"question": "Comment un zero rencontre un un ?", "reponse": "Ils font 10 tours ensemble."},
    {"question": "Quelle est la plante qui fait le plus peur ?", "reponse": "La pivoine-gouin."},
    {"question": "Pourquoi le cafe est-il en colere ?", "reponse": "Parce qu'on l'a moulu."},
    {"question": "Pourquoi le the est-il calme ?", "reponse": "Parce qu'il est infuse de sagesse."},
    {"question": "Pourquoi les nuages n'ont pas de smartphone ?", "reponse": "Parce que le signal passe au travers."},
    {"question": "Pourquoi le soleil ne va-t-il pas a l'ecole ?", "reponse": "Parce qu'il brille deja sans etudier."},
    {"question": "Pourquoi la lune est-elle timide ?", "reponse": "Parce qu'elle se cache tous les jours."},
    {"question": "Que dit le vent a un arbre ?", "reponse": "Penche-toi, j'arrive !"},
    {"question": "Pourquoi le feu est-il impatient ?", "reponse": "Parce qu'il est toujours en flammes."},
    {"question": "Que fait un cadavre au karaoke ?", "reponse": "Il chante de toutes ses os."},
    {"question": "Que dit un squelette a son fils ?", "reponse": "On a du pain sur la planche."},
    {"question": "Pourquoi le miroir est triste ?", "reponse": "Parce qu'il voit tout le temps quelqu'un de faux."},
    {"question": "Pourquoi l'interrupteur est-il seul ?", "reponse": "Parce qu'il allume tout le monde puis s'eteint."},
    {"question": "Pourquoi les chaussettes disparaissent dans la machine ?", "reponse": "Parce qu'elles partent en voyage sans les chaussures."},
    {"question": "Que dit une clef a une serrure ?", "reponse": "Tu me fais tourner la tete."},
    {"question": "Pourquoi le reveil est-il fache ?", "reponse": "Parce qu'on le tape tous les matins."},
    {"question": "Pourquoi le lit est-il fatigue ?", "reponse": "Parce qu'il porte tout le monde sur son dos."},
    {"question": "Que dit le papier toilette au rouleau ?", "reponse": "Ensemble jusqu'au bout !"},
    {"question": "Pourquoi la chaise pleure-t-elle ?", "reponse": "Parce qu'elle est toujours assise sur elle-meme."},
    {"question": "Que dit une ampoule qui grille ?", "reponse": "C'etait fulgurant."},
    {"question": "Pourquoi le savon est-il glissant ?", "reponse": "Parce qu'il a toujours la main douce."},
    {"question": "Pourquoi la brosse a dents est-elle matinale ?", "reponse": "Parce que tout le monde la croque des le reveil."},
    {"question": "Pourquoi la douche chante-t-elle ?", "reponse": "Parce que l'acoustique est parfaite."},
    {"question": "Pourquoi le papier est-il silencieux ?", "reponse": "Parce qu'il ne parle qu'avec un stylo."},
    {"question": "Pourquoi le stylo est-il bavard ?", "reponse": "Parce qu'il a toujours quelque chose a dire."},
    {"question": "Pourquoi la gomme est-elle oublieuse ?", "reponse": "Parce qu'elle efface tout."},
    {"question": "Pourquoi le crayon est-il discret ?", "reponse": "Parce qu'il se laisse effacer sans rien dire."},
    {"question": "Pourquoi l'horloge danse-t-elle ?", "reponse": "Parce qu'elle a toujours le tempo."},
    {"question": "Que dit un musicien a son piano ?", "reponse": "On s'accorde a merveille."},
    {"question": "Pourquoi le violon pleure-t-il ?", "reponse": "Parce qu'on le frotte."},
    {"question": "Pourquoi la flute est-elle mince ?", "reponse": "Parce qu'on souffle tout le temps dessus."},
    {"question": "Pourquoi la guitare est-elle emotive ?", "reponse": "Parce qu'on lui pince les cordes."},
    {"question": "Pourquoi le tambour est-il colerique ?", "reponse": "Parce qu'on le tape sans arret."},
    {"question": "Que dit le maracas a son ami bongo ?", "reponse": "On va faire du bruit ensemble."},
    {"question": "Pourquoi la trompette est-elle fiere ?", "reponse": "Parce qu'elle sonne toujours haut."},
    {"question": "Pourquoi le xylophone est-il amusant ?", "reponse": "Parce qu'il joue sur plusieurs tons."},
    {"question": "Pourquoi l'accordeon est-il essoufflant ?", "reponse": "Parce qu'il pousse et tire sans cesse."},
    {"question": "Pourquoi le microphone est-il bavard ?", "reponse": "Parce qu'il amplifie toutes les histoires."},
    {"question": "Pourquoi le casque est-il solitaire ?", "reponse": "Parce qu'il se met entre deux oreilles."},
    {"question": "Pourquoi la radio est-elle inspirante ?", "reponse": "Parce qu'elle donne le rythme de la journee."},
    {"question": "Pourquoi la television est-elle fatigante ?", "reponse": "Parce qu'elle nous scotche."},
    {"question": "Pourquoi le canape aime-t-il les films ?", "reponse": "Parce qu'il s'installe confortablement."},
    {"question": "Pourquoi le tapis est-il relax ?", "reponse": "Parce que tout le monde marche sur lui."},
    {"question": "Pourquoi le plafond est-il haut ?", "reponse": "Parce qu'il a pris de la hauteur."},
    {"question": "Pourquoi le sol est-il humble ?", "reponse": "Parce qu'il reste en bas."},
    {"question": "Pourquoi la porte grince-t-elle ?", "reponse": "Parce qu'elle a besoin d'huile et de calin."},
    {"question": "Pourquoi la fenetre reve-t-elle ?", "reponse": "Parce qu'elle regarde dehors toute la journee."},
    {"question": "Pourquoi le mur est-il patient ?", "reponse": "Parce qu'il ne bouge jamais."},
    {"question": "Pourquoi l'escalier est-il ambigu ?", "reponse": "Parce qu'il monte et descend en meme temps."},
    {"question": "Pourquoi l'ascenseur est-il poli ?", "reponse": "Parce qu'il dit bonjour a chaque etage."},
    {"question": "Pourquoi la boite aux lettres est-elle jalouse ?", "reponse": "Parce qu'elle est toujours en attente de nouvelles."},
    {"question": "Pourquoi le facteur siffle-t-il ?", "reponse": "Parce qu'il a toujours le moral au courrier."},
    {"question": "Pourquoi le velo est-il agile ?", "reponse": "Parce qu'il tient en equilibre sur deux doigts de pieds."},
    {"question": "Pourquoi le skateboard est-il cool ?", "reponse": "Parce qu'il roule sans se prendre la tete."},
    {"question": "Pourquoi les rollers sont-ils synchros ?", "reponse": "Parce qu'ils avancent toujours ensemble."},
    {"question": "Pourquoi le surf est-il relax ?", "reponse": "Parce qu'il prend la vague comme elle vient."},
    {"question": "Pourquoi le ski est-il rapide ?", "reponse": "Parce qu'il ne traine pas sur la neige."},
    {"question": "Pourquoi le snowboard est-il stylé ?", "reponse": "Parce qu'il glisse avec classe."},
    {"question": "Pourquoi le parapente est-il libre ?", "reponse": "Parce qu'il depend seulement du vent."},
    {"question": "Pourquoi le saut a l'elastique est-il philosophique ?", "reponse": "Parce qu'il te fait reflechir en tombant."},
    {"question": "Pourquoi le plongeoir est-il emotif ?", "reponse": "Parce qu'il est toujours au bord."},
    {"question": "Pourquoi la piscine est-elle discrete ?", "reponse": "Parce qu'elle absorbe tous les secrets des nageurs."},
    {"question": "Pourquoi le lac est-il sage ?", "reponse": "Parce qu'il reflete tout sans rien dire."},
    {"question": "Pourquoi la riviere est-elle bavarde ?", "reponse": "Parce qu'elle coule tout le temps."},
    {"question": "Pourquoi la mer est-elle salee ?", "reponse": "Parce qu'il y a des morues qui pleurent beaucoup."},
    {"question": "Pourquoi l'ocean est-il profond ?", "reponse": "Parce qu'il reflechit vraiment."},
    {"question": "Pourquoi la montagne est-elle solennelle ?", "reponse": "Parce qu'elle sait prendre de la hauteur."},
    {"question": "Pourquoi la vallee est-elle accueillante ?", "reponse": "Parce qu'elle tend toujours les bras."},
    {"question": "Pourquoi la foret est-elle secrete ?", "reponse": "Parce qu'elle cache beaucoup d'arbres."},
    {"question": "Pourquoi le desert est-il silencieux ?", "reponse": "Parce que personne ne repond aux questions du sable."},
    {"question": "Pourquoi la jungle est-elle tape-a-l-oeil ?", "reponse": "Parce qu'elle est pleine de perroquets."},
    {"question": "Pourquoi la banquise est-elle polie ?", "reponse": "Parce qu'elle ne rit jamais a froid."},
    {"question": "Pourquoi l'etoile filante va vite ?", "reponse": "Parce qu'elle a peu de temps pour realiser les voeux."},
    {"question": "Pourquoi la planete tourne-t-elle ?", "reponse": "Parce que sinon on aurait le mal de planete."},
    {"question": "Pourquoi les meteorites tombent-elles ?", "reponse": "Parce qu'elles oublient de regarder en bas."},
    {"question": "Pourquoi la galaxie est-elle mysterieuse ?", "reponse": "Parce qu'elle brille dans le secret."},
    {"question": "Pourquoi l'univers est-il vaste ?", "reponse": "Parce qu'il a de la place pour tout le monde."},
    {"question": "Pourquoi le trou noir est-il timide ?", "reponse": "Parce qu'il absorbe tout sauf les compliments."},
    {"question": "Pourquoi la comete est-elle elegante ?", "reponse": "Parce qu'elle a toujours une queue stylée."},
    {"question": "Pourquoi Mars est-elle rouge ?", "reponse": "Parce qu'elle a honte de sa petite taille."},
    {"question": "Pourquoi Jupiter est-il fier ?", "reponse": "Parce qu'il est le plus gros."},
    {"question": "Pourquoi Saturne a-t-il des anneaux ?", "reponse": "Parce qu'il a plein de fans fideles."},
    {"question": "Pourquoi Uranus fait rire ?", "reponse": "A cause du nom, surtout en anglais."},
    {"question": "Pourquoi Neptune est-il bleu ?", "reponse": "Parce qu'il est loin du soleil et deprime."},
    {"question": "Pourquoi Pluton est-il mal aime ?", "reponse": "Parce qu'on l'a declassifie."},
    {"question": "Pourquoi le soleil a-t-il la grosse tete ?", "reponse": "Parce que tout tourne autour de lui."},
    {"question": "Pourquoi la Terre est-elle ronde ?", "reponse": "Pour eviter les coins sombres."},
    {"question": "Pourquoi la lune ne se couche jamais ?", "reponse": "Parce qu'elle n'a pas de lit."},
    {"question": "Pourquoi l'espace est-il sombre ?", "reponse": "Parce que l'abonnement a l'electricite n'y est pas encore arrive."},
    {"question": "Pourquoi les aliens ne viennent-ils pas sur Terre ?", "reponse": "Parce qu'ils n'ont pas de GPS a jour."},
    {"question": "Pourquoi les OVNIs volent-ils ?", "reponse": "Parce qu'ils ont trop bu en soiree galactique."},

    # === Sports ===
    {"question": "Pourquoi les footballeurs courent-ils tout le temps ?", "reponse": "Parce que la pelouse ne vient pas a eux."},
    {"question": "Que dit un arbitre qui a faim ?", "reponse": "Je me mange une jaune et une rouge."},
    {"question": "Pourquoi les basketteurs sont-ils grands ?", "reponse": "Parce qu'ils ont la tete dans les paniers."},
    {"question": "Pourquoi les nageurs ont-ils de grandes epaules ?", "reponse": "Parce qu'ils portent toute l'eau."},
    {"question": "Pourquoi les marathoniens ont-ils mal aux pieds ?", "reponse": "Parce qu'ils ne prennent pas le bus."},
    {"question": "Que dit un coureur fatigue ?", "reponse": "Allez, juste encore 42 bornes."},
    {"question": "Pourquoi le golfeur a-t-il deux pantalons ?", "reponse": "Au cas ou il ferait un trou en un."},
    {"question": "Pourquoi le tennisman parle-t-il tout seul ?", "reponse": "Parce qu'il echange avec lui-meme."},
    {"question": "Pourquoi le gymnaste tombe-t-il rarement ?", "reponse": "Parce qu'il a l'equilibre dans la tete."},
    {"question": "Pourquoi le cycliste prend-il toujours l'apero ?", "reponse": "Parce qu'il aime les doux cafes."},

    # === Ecole ===
    {"question": "Pourquoi les eleves dorment-ils en classe ?", "reponse": "Parce que le prof est tres endormant."},
    {"question": "Que dit un crayon triste ?", "reponse": "Je me suis casse la mine."},
    {"question": "Pourquoi le cahier pleure-t-il ?", "reponse": "Parce qu'on ecrit sa vie dessus."},
    {"question": "Que dit le tableau au feutre ?", "reponse": "N'ecris pas trop fort, je suis fragile."},
    {"question": "Pourquoi l'ordinateur a-t-il des caries ?", "reponse": "Parce qu'il mange trop de cookies."},
    {"question": "Pourquoi la craie grince-t-elle ?", "reponse": "Parce qu'elle n'aime pas qu'on la frotte."},
    {"question": "Pourquoi le bureau est-il encombre ?", "reponse": "Parce que tout le monde y pose des problemes."},
    {"question": "Pourquoi la regle est-elle droite ?", "reponse": "Parce qu'elle n'aime pas les ecarts."},
    {"question": "Pourquoi la calculatrice est-elle fatiguee ?", "reponse": "Parce qu'elle passe sa vie a compter."},
    {"question": "Pourquoi le classeur est-il organise ?", "reponse": "Parce qu'il deteste la pagaille."},

    # === Famille ===
    {"question": "Pourquoi la maman de Toto chante-t-elle ?", "reponse": "Parce qu'elle couvre ses betises."},
    {"question": "Pourquoi les grand-meres aiment les bonbons ?", "reponse": "Parce qu'elles en gardent pour les petits-enfants."},
    {"question": "Pourquoi les papas ronflent-ils ?", "reponse": "Parce qu'ils sont les rois du canape."},
    {"question": "Que fait un grand-pere toute la journee ?", "reponse": "Il raconte la meme histoire a chaque invite."},
    {"question": "Pourquoi le cousin eloigne est-il toujours invite ?", "reponse": "Pour rappeler qu'on a de la famille."},
    {"question": "Pourquoi les bebes pleurent-ils la nuit ?", "reponse": "Pour s'entrainer a reveiller leurs parents."},
    {"question": "Pourquoi les freres se disputent-ils ?", "reponse": "Parce que l'autre respire trop fort."},
    {"question": "Pourquoi les soeurs partagent-elles tout ?", "reponse": "Surtout les vetements sans demander."},
    {"question": "Pourquoi les oncles font-ils des vieux calembours ?", "reponse": "Parce qu'ils n'ont plus de public ailleurs."},
    {"question": "Pourquoi les tantes offrent-elles des pulls ?", "reponse": "Parce que le gout est moins important que l'amour."},

    # === Mystere ===
    {"question": "Qu'est-ce qui est noir, blanc et rouge partout ?", "reponse": "Un pingouin qui rougit."},
    {"question": "Qu'est-ce qui est bleu, blanc, rouge et flotte ?", "reponse": "Un Francais en vacances."},
    {"question": "Qu'est-ce qui entre dur et sort mou ?", "reponse": "Un chewing-gum !"},
    {"question": "Qu'est-ce qui est grand et plat ?", "reponse": "Un playa sans eau."},
    {"question": "Qu'est-ce qui traverse le ciel ?", "reponse": "Un mot, quand on le lance en l'air."},
    {"question": "Qu'est-ce qui tombe sans se faire mal ?", "reponse": "La pluie."},
    {"question": "Qu'est-ce qui court sans jambes ?", "reponse": "Le temps."},
    {"question": "Qu'est-ce qui parle sans bouche ?", "reponse": "Un livre !"},
    {"question": "Qu'est-ce qui voit sans yeux ?", "reponse": "Une camera."},
    {"question": "Qu'est-ce qui mange sans dents ?", "reponse": "La rouille !"},

    # === Questions existentielles ===
    {"question": "Pourquoi on dit que c'est la nuit quand il fait noir ?", "reponse": "Parce que sinon, on dirait juste c'est eteint."},
    {"question": "Pourquoi dit-on sourire quand la bouche est dure ?", "reponse": "Parce que sous les dents, ca rit !"},
    {"question": "Pourquoi les maisons ont-elles des fenetres ?", "reponse": "Pour mieux regarder les voisins."},
    {"question": "Pourquoi un silence est-il ecrasant ?", "reponse": "Parce qu'il pese deux bises lourdes."},
    {"question": "Pourquoi on dit prendre une douche ?", "reponse": "Parce qu'elle ne vient jamais d'elle-meme."},
    {"question": "Pourquoi le zero n'a-t-il pas de personnalite ?", "reponse": "Parce qu'il n'est rien."},
    {"question": "Pourquoi dit-on un paquet ?", "reponse": "Parce qu'on y a emballe plein de choses."},
    {"question": "Pourquoi un chat a-t-il neuf vies ?", "reponse": "Parce qu'avec une seule, il tomberait plus souvent."},
    {"question": "Pourquoi les miroirs ne disent rien ?", "reponse": "Parce qu'ils reflechissent."},
    {"question": "Pourquoi les etoiles clignotent-elles ?", "reponse": "Parce qu'elles nous font des clins d'oeil."},

    # === Encore des courtes ===
    {"question": "Un bonhomme de neige rencontre un soleil :", "reponse": "Il fait une tete de flaque."},
    {"question": "Qu'est-ce que dit une boulangere a son mari ?", "reponse": "T'es le beurre de ma vie."},
    {"question": "Un pull rencontre un gilet :", "reponse": "Zipper, moi je suis ouvert."},
    {"question": "Un chien voit son ombre :", "reponse": "Wahou, j'ai un jumeau noir !"},
    {"question": "Un oeuf dur a un oeuf mollet :", "reponse": "T'es trop sensible."},
    {"question": "Un ballon rencontre une aiguille :", "reponse": "Je crains le pire."},
    {"question": "Un sable dit au soleil :", "reponse": "T'as une chaleur tropicale aujourd'hui !"},
    {"question": "Un paratonnerre voit un orage :", "reponse": "Enfin de l'action !"},
    {"question": "Un parapluie face au vent :", "reponse": "Tu me retournes le coeur."},
    {"question": "Une corde a un fil :", "reponse": "On tient bon ensemble."},
    {"question": "Un nuage voit le soleil :", "reponse": "Je fonds pour toi."},
    {"question": "Un arc-en-ciel a la pluie :", "reponse": "Sans toi, je n'existerais pas."},
    {"question": "Un flocon a son cousin glaçon :", "reponse": "On fond tous un jour."},
    {"question": "Une bougie a une allumette :", "reponse": "Merci de m'avoir allumee."},
    {"question": "Un feu d'artifice a une etoile :", "reponse": "Je ne brille qu'un instant, toi toujours."},
    {"question": "Une fleur a son jardinier :", "reponse": "Arrose-moi, je suis en pleine floraison."},
    {"question": "Un arbre au printemps :", "reponse": "Enfin, ca repousse !"},
    {"question": "Une feuille a son arbre :", "reponse": "Je m'envole, mais je reviendrai."},
    {"question": "Un pollen a une abeille :", "reponse": "Emmene-moi loin d'ici."},
    {"question": "Un miel a une tartine :", "reponse": "Ensemble, on colle parfaitement."},
    {"question": "Un lapin a une carotte :", "reponse": "Je te mange des yeux."},
    {"question": "Une souris a un fromage :", "reponse": "Coup de foudre pour toi."},
    {"question": "Un poisson a un hamecon :", "reponse": "Tu es un piege !"},
    {"question": "Une mouette a un bateau :", "reponse": "Je te suis partout."},
    {"question": "Un requin a une meduse :", "reponse": "Tu es totalement gelee."},
    {"question": "Un perroquet a un miroir :", "reponse": "Coucou, coucou, coucou."},
    {"question": "Un aigle a un moineau :", "reponse": "Je vise plus haut que toi."},
    {"question": "Un cocorico a une poule :", "reponse": "C'est moi qui decide quand c'est l'aube."},
    {"question": "Un ver de terre a un oiseau :", "reponse": "Pitie, pas encore !"},
    {"question": "Une coccinelle a une fourmi :", "reponse": "Tu vois, j'ai des spots moi aussi."},

    # === Et encore ===
    {"question": "Pourquoi on dit qu'on pique un fou rire ?", "reponse": "Parce que le rire est un voleur de serieux."},
    {"question": "Pourquoi on dit qu'on gobe une histoire ?", "reponse": "Parce qu'on l'avale sans verifier."},
    {"question": "Pourquoi un menteur a le nez qui s'allonge ?", "reponse": "Parce que la verite se cache dedans."},
    {"question": "Pourquoi les enfants aiment-ils les bonbons ?", "reponse": "Parce qu'ils n'ont pas encore la carte bancaire."},
    {"question": "Pourquoi les adultes boivent du cafe ?", "reponse": "Parce que les bonbons ne suffisent plus."},
    {"question": "Pourquoi les vieux parlent fort ?", "reponse": "Parce que le silence les ecoute mal."},
    {"question": "Pourquoi les ados portent-ils des capuches ?", "reponse": "Pour ne pas voir le monde."},
    {"question": "Pourquoi les bebes sourient-ils ?", "reponse": "Parce qu'ils savent un secret qu'on a oublie."},
    {"question": "Pourquoi les parents crient-ils ?", "reponse": "Parce que leur wifi interieur est coupe."},
    {"question": "Pourquoi les profs sont fatigues ?", "reponse": "Parce qu'ils expliquent trois fois la meme chose."},

    # === Dernieres ===
    {"question": "Un cafe court rencontre un grand cafe :", "reponse": "Cours plus vite !"},
    {"question": "Un short et un pantalon :", "reponse": "Bas-moi les pattes !"},
    {"question": "Une pomme parle a une poire :", "reponse": "On va en compote ensemble."},
    {"question": "Un bouchon a une bouteille :", "reponse": "Je suis la pour te boucher."},
    {"question": "Un timbre a une enveloppe :", "reponse": "Colle-toi a moi, on va voyager."},
    {"question": "Une allumette a son cousin briquet :", "reponse": "T'es trop puissant pour moi."},
    {"question": "Une paille a un bol :", "reponse": "Je suis ici juste pour aspirer."},
    {"question": "Un cube a un ballon :", "reponse": "On n'a pas les memes arrondis."},
    {"question": "Un glaçon a un verre d'eau :", "reponse": "Je tombe dedans jusqu'a fondre."},
    {"question": "Une plume a un oreiller :", "reponse": "Ensemble, on est legers."},
    {"question": "Un ressort a un canape :", "reponse": "Je te soutiens pour la vie."},
    {"question": "Un balai a une pelle :", "reponse": "On fait equipe contre la poussiere."},
    {"question": "Une eponge a un savon :", "reponse": "Mouillons-nous ensemble."},
    {"question": "Un rideau a une fenetre :", "reponse": "Je te cache mais je te protege."},
    {"question": "Un oreiller a une couette :", "reponse": "Bonne nuit, dors serre."},
    {"question": "Une clef USB a un ordinateur :", "reponse": "Je porte tous tes secrets."},
    {"question": "Un cable a une prise :", "reponse": "On se branche ensemble."},
    {"question": "Un ecran a un clavier :", "reponse": "Tu tapes, je reponds."},
    {"question": "Une souris a un tapis :", "reponse": "Je roule juste sur toi."},
    {"question": "Un stylet a une tablette :", "reponse": "Je caresse ta surface."},
    {"question": "Un smartphone a un chargeur :", "reponse": "Sans toi, je suis mort."},
    {"question": "Une application a un utilisateur :", "reponse": "Notifie-moi si tu m'aimes."},
    {"question": "Un pixel a un ecran :", "reponse": "Je suis petit mais important."},
    {"question": "Un emoji a un mot :", "reponse": "Je vaux mille lettres."},
    {"question": "Un hashtag a une phrase :", "reponse": "Sans moi, tu n'existes pas en ligne."},
    {"question": "Une notification a un cerveau :", "reponse": "Pardon, mais je m'invite souvent."},
    {"question": "Un like a un post :", "reponse": "Tu as fait ma journee."},
    {"question": "Un commentaire a un article :", "reponse": "Je rallonge l'histoire."},
    {"question": "Un pull a une echarpe :", "reponse": "Ensemble on bat le froid."},
    {"question": "Une paire de lunettes a un nez :", "reponse": "Tu es mon socle."},
    {"question": "Un bonnet a une tete :", "reponse": "Je te chauffe le crane."},
    {"question": "Des gants a des mains :", "reponse": "On tient bon au froid."},
    {"question": "Un manteau a un pull :", "reponse": "Je prends tout sur moi."},
    {"question": "Un parapluie a un impermeable :", "reponse": "A nous deux, la pluie n'a aucune chance."},
    {"question": "Une botte a une flaque :", "reponse": "Je saute, tu eclabousses."},
    {"question": "Un puits a une source :", "reponse": "Je garde ton eau en secret."},
    {"question": "Une rose a une epine :", "reponse": "Ma beaute a un prix."},
    {"question": "Un cactus a un desert :", "reponse": "Je resiste, parce que je pique."},
    {"question": "Un sapin a un pere Noel :", "reponse": "Accroche-toi, ca va briller."},
    {"question": "Un flocon a une rue :", "reponse": "Je te blanchis pour la nuit."},
    {"question": "Une ski a une piste :", "reponse": "On glisse sans se poser de questions."},
    {"question": "Un traineau a un renne :", "reponse": "Tu m'emmenes loin."},
    {"question": "Un cadeau a un papier :", "reponse": "Emballe-moi, on fera la surprise."},
    {"question": "Une guirlande a un sapin :", "reponse": "Je te mets en lumiere."},
    {"question": "Un chocolat a un calendrier de l'Avent :", "reponse": "Chaque jour je disparais un peu."},
    {"question": "Un petard a un feu d'artifice :", "reponse": "Je suis son petit frere bruyant."},
    {"question": "Un confetti a un balais :", "reponse": "Je voyage, tu me rattrapes."},
    {"question": "Un ballon a une fete :", "reponse": "Je gonfle ou je disparais."},
    {"question": "Un gateau d'anniversaire a une bougie :", "reponse": "Fais un voeu avant que je sois mange."},
    {"question": "Une chanson a une fete :", "reponse": "Sans moi, tout le monde regarde son telephone."},
    {"question": "Une piñata a un baton :", "reponse": "Frappe fort, je suis pleine."},
    {"question": "Un disque a une platine :", "reponse": "Fais-moi tourner la tete."},
    {"question": "Un micro a un chanteur :", "reponse": "Parle-moi fort."},
    {"question": "Une corde a une guitare :", "reponse": "Pince-moi, j'existe."},
    {"question": "Un solo a un duo :", "reponse": "Je suis tout seul, mais je brille."},
    {"question": "Une partition a un musicien :", "reponse": "Lis-moi sans te perdre."},
    {"question": "Un rythme a un batteur :", "reponse": "Garde le cap."},
    {"question": "Un beat a une basse :", "reponse": "Sans toi, pas de groove."},
    {"question": "Un remix a un original :", "reponse": "Je te modernise un peu."},
    {"question": "Un echantillon a un morceau :", "reponse": "Je suis un petit bout qui brille."},

    # === Encore plus ===
    {"question": "Pourquoi le sel est-il si seul ?", "reponse": "Parce que le poivre est jaloux."},
    {"question": "Pourquoi la poele adore-t-elle le feu ?", "reponse": "Parce qu'il la chauffe a point."},
    {"question": "Pourquoi la casserole chantonne-t-elle ?", "reponse": "Parce que l'eau bout et l'inspire."},
    {"question": "Pourquoi le four est-il genereux ?", "reponse": "Parce qu'il cuit pour tout le monde."},
    {"question": "Pourquoi le frigo est-il froid ?", "reponse": "Parce qu'il n'a pas de cheminee interieure."},
    {"question": "Pourquoi le congelo est-il ferme ?", "reponse": "Parce qu'il n'aime pas les coulures emotionnelles."},
    {"question": "Pourquoi le micro-ondes est-il bavard ?", "reponse": "Parce qu'il bippe tout le temps."},
    {"question": "Pourquoi la cafetiere est-elle matinale ?", "reponse": "Parce qu'elle croit que l'aube commence avec elle."},
    {"question": "Pourquoi la bouilloire siffle-t-elle ?", "reponse": "Parce qu'elle prefere chanter plutot que d'exploser."},
    {"question": "Pourquoi le grille-pain est-il dragueur ?", "reponse": "Parce qu'il ejecte toujours avec style."},
    {"question": "Pourquoi la bouteille est-elle triste ?", "reponse": "Parce qu'elle est toujours prise pour une jetable."},
    {"question": "Pourquoi le verre est-il fragile ?", "reponse": "Parce qu'il ressent chaque choc."},
    {"question": "Pourquoi la fourchette est-elle piquante ?", "reponse": "Parce qu'elle a du mordant."},
    {"question": "Pourquoi le couteau est-il affute ?", "reponse": "Parce qu'il ne laisse rien passer."},
    {"question": "Pourquoi la cuillere est-elle douce ?", "reponse": "Parce qu'elle comprend la soupe."},
    {"question": "Pourquoi l'assiette est-elle accueillante ?", "reponse": "Parce qu'elle reçoit tout le monde."},
    {"question": "Pourquoi la nappe est-elle tolerante ?", "reponse": "Parce qu'elle supporte les taches."},
    {"question": "Pourquoi la serviette est-elle douce ?", "reponse": "Parce qu'elle essuie les pires desastres."},
    {"question": "Pourquoi le tablier est-il protecteur ?", "reponse": "Parce qu'il prend les projections a ta place."},
    {"question": "Pourquoi la spatule est-elle diplomate ?", "reponse": "Parce qu'elle retourne la situation."},
    {"question": "Pourquoi la louche est-elle genereuse ?", "reponse": "Parce qu'elle sert chacun en entier."},
    {"question": "Pourquoi le rouleau a patisserie est-il stresse ?", "reponse": "Parce qu'il passe sa vie sous pression."},
    {"question": "Pourquoi la planche a decouper est-elle patiente ?", "reponse": "Parce qu'elle encaisse tous les coups."},
    {"question": "Pourquoi l'epluche-legumes est-il modeste ?", "reponse": "Parce qu'il reste dans le tiroir."},
    {"question": "Pourquoi le presse-ail pleure-t-il ?", "reponse": "Parce qu'on le broie de larmes odorantes."},
]
